const db = require('../config/db');

// --- COMPREHENSIVE REAL INSTITUTION DATASET (600+ ENTRIES) ---
const rawData = {
  'Ariyalur': [
    { name: 'Government Arts and Science College, Ariyalur', type: 'college' },
    { name: 'Government Polytechnic College, Ariyalur', type: 'college' },
    { name: 'Government Engineering College, Ariyalur', type: 'college' },
    { name: 'Meenakshi Ramasamy Arts and Science College', type: 'college' },
    { name: 'Vinayaga Arts and Science College', type: 'college' },
    { name: 'Modern Arts and Science College, Ariyalur', type: 'college' },
    { name: 'Government Higher Secondary School, Ariyalur', type: 'school' },
    { name: 'Government Boys Higher Secondary School, Jayankondam', type: 'school' },
    { name: 'Government Girls Higher Secondary School, Ariyalur', type: 'school' },
    { name: 'St. Michael\'s Higher Secondary School', type: 'school' },
    { name: 'Montfort Higher Secondary School, Ariyalur', type: 'school' },
    { name: 'Government ITI, Ariyalur', type: 'college' },
    { name: 'District Institute of Education and Training (DIET), Ariyalur', type: 'college' },
    { name: 'Modern Matriculation School, Ariyalur', type: 'school' },
    { name: 'Sabari Matriculation School', type: 'school' },
    { name: 'Amirtham Matriculation School', type: 'school' }
  ],
  'Chengalpattu': [
    { name: 'Chengalpattu Medical College', type: 'college' },
    { name: 'Government Arts College, Chengalpattu', type: 'college' },
    { name: 'SRM Institute of Science and Technology, Kattankulathur', type: 'college' },
    { name: 'Crescent Institute of Science and Technology, Vandalur', type: 'college' },
    { name: 'SSN College of Engineering, Kalavakkam', type: 'college' },
    { name: 'VIT Chennai Campus, Melakottaiyur', type: 'college' },
    { name: 'Asan Memorial College of Arts and Science', type: 'college' },
    { name: 'St. Joseph\'s College of Engineering, OMR', type: 'college' },
    { name: 'Jeppiaar Engineering College', type: 'college' },
    { name: 'Dhaanish Ahmed College of Engineering', type: 'college' },
    { name: 'Prince Shri Venkateshwara Padmavathy Engineering College', type: 'college' },
    { name: 'Government Higher Secondary School, Chengalpattu', type: 'school' },
    { name: 'Kendriya Vidyalaya, Tambaram (AF Station)', type: 'school' },
    { name: 'Velammal Vidyalaya, Maraimalai Nagar', type: 'school' },
    { name: 'St. Mary\'s Matriculation School, Chengalpattu', type: 'school' },
    { name: 'Guduvanchery Government Higher Secondary School', type: 'school' }
  ],
  'Chennai': [
    { name: 'Indian Institute of Technology Madras (IIT Madras)', type: 'college' },
    { name: 'Madras Medical College, Chennai', type: 'college' },
    { name: 'Loyola College, Chennai', type: 'college' },
    { name: 'Stella Maris College, Chennai', type: 'college' },
    { name: 'Madras Christian College', type: 'college' },
    { name: 'Presidency College, Chennai', type: 'college' },
    { name: 'Ethiraj College for Women', type: 'college' },
    { name: 'Madras Institute of Technology', type: 'college' },
    { name: 'Alagappa College of Technology', type: 'college' },
    { name: 'Anna University, Guindy', type: 'college' },
    { name: 'Stanley Medical College, Chennai', type: 'college' },
    { name: 'Kilpauk Medical College, Chennai', type: 'college' },
    { name: 'Government Omandurar Medical College, Chennai', type: 'college' },
    { name: 'Women\'s Christian College, Chennai', type: 'college' },
    { name: 'Queen Mary\'s College, Chennai', type: 'college' },
    { name: 'New College, Chennai', type: 'college' },
    { name: 'Pachaiyappa\'s College, Chennai', type: 'college' },
    { name: 'Guru Nanak College', type: 'college' },
    { name: 'M.O.P. Vaishnav College for Women', type: 'college' },
    { name: 'Justice Basheer Ahmed Sayeed College for Women', type: 'college' },
    { name: 'Meenakshi College for Women', type: 'college' },
    { name: 'Srimathi Devkunvar Nanalal Bhatt Vaishnav College for Women', type: 'college' },
    { name: 'Dwaraka Doss Goverdhan Doss Vaishnav College', type: 'college' },
    { name: 'Agurchand Manmull Jain College', type: 'college' },
    { name: 'Ramakrishna Mission Vivekananda College', type: 'college' },
    { name: 'Hindustan College of Arts and Science', type: 'college' },
    { name: 'Mohamed Sathak College of Arts and Science', type: 'college' },
    { name: 'Patrician College of Arts and Science', type: 'college' },
    { name: 'Chellammal Women\'s College', type: 'college' },
    { name: 'Dr. MGR-Janaki College of Arts and Science for Women', type: 'college' },
    { name: 'Government College of Fine Arts, Chennai', type: 'college' },
    { name: 'Jayagovind Harigopal Agarwal Agarsen College', type: 'college' },
    { name: 'Mar Gregorios College of Arts and Science, Chennai', type: 'college' },
    { name: 'Shri Shankarlal Sundarbai Shasun Jain College for Women', type: 'college' },
    { name: 'Sir Theagaraya College', type: 'college' },
    { name: 'St. Thomas College, Chennai', type: 'college' },
    { name: 'T S Narayanaswami College of Arts and Science', type: 'college' },
    { name: 'Thiruthangal Nadar College', type: 'college' },
    { name: 'Aalim Muhammed Salegh College of Engineering', type: 'college' },
    { name: 'Agni College of Technology', type: 'college' },
    { name: 'Aksheyaa College of Engineering', type: 'college' },
    { name: 'Alpha College of Engineering', type: 'college' },
    { name: 'Jerusalem College of Engineering, Chennai', type: 'college' },
    { name: 'Loyola-ICAM College of Engineering and Technology', type: 'college' },
    { name: 'Saveetha Engineering College', type: 'college' },
    { name: 'Sree Sastha Institute of Engineering and Technology', type: 'college' },
    { name: 'Sri Sai Ram Engineering College', type: 'college' },
    { name: 'Sri Sairam Institute of Technology', type: 'college' },
    { name: 'Sri Sivasubramaniya Nadar College of Engineering', type: 'college' },
    { name: 'Sri Venkateswara College of Engineering', type: 'college' },
    { name: 'SRM Institute of Science and Technology, Ramapuram', type: 'college' },
    { name: 'Sri Ramachandra Institute of Higher Education and Research, Porur', type: 'college' },
    { name: 'ACS Medical College and Hospital, Velappanchavadi', type: 'college' },
    { name: 'Bhaarath Medical College and Hospital, Selaiyur', type: 'college' },
    { name: 'ESIC Medical College & PGIMSR, Chennai', type: 'college' },
    { name: 'Tagore Medical College and Hospital, Rathinamangalam', type: 'college' },
    { name: 'Dr. Ambedkar Government Law College, Chennai', type: 'college' },
    { name: 'Tamil Nadu Dr. Ambedkar Law University, Chennai', type: 'college' },
    { name: 'School of Excellence in Law, Chennai', type: 'college' },
    { name: 'Madras Veterinary College, Vepery', type: 'college' },
    { name: 'Tamil Nadu Physical Education and Sports University, Chennai', type: 'college' },
    { name: 'Asian College of Journalism, Chennai', type: 'college' },
    { name: 'National Institute of Fashion Technology, Chennai', type: 'college' },
    { name: 'Kalakshetra Foundation, Adyar', type: 'college' },
    { name: 'Meenakshi Sundararajan Engineering College, Kodambakkam', type: 'college' },
    { name: 'Panimalar Engineering College, Poonamallee', type: 'college' },
    { name: 'Rajalakshmi Engineering College, Thandalam', type: 'college' },
    { name: 'St. Joseph\'s College of Engineering, Sholinganallur', type: 'college' },
    { name: 'Velammal Engineering College, Surapet', type: 'college' },
    { name: 'Sathyabama Institute of Science and Technology, Sholinganallur', type: 'college' },
    { name: 'Easwari Engineering College, Ramapuram', type: 'college' },
    { name: 'Misrimal Navajee Munoth Jain Engineering College', type: 'college' },
    { name: 'Anand Institute of Higher Technology', type: 'college' },
    { name: 'Jeppiaar Engineering College', type: 'college' },
    { name: 'K.C.S. Kasi Nadar College of Arts & Science', type: 'college' },
    { name: 'Tamil Nadu Government Music College, Chennai', type: 'college' },
    { name: 'Padma Seshadri Bala Bhavan (PSBB) Senior Secondary School, Nungambakkam', type: 'school' },
    { name: 'D.A.V. Boys Senior Secondary School, Gopalapuram', type: 'school' },
    { name: 'Chettinad Vidyashram, R. A. Puram', type: 'school' },
    { name: 'St. Bede\'s Anglo Indian Higher Secondary School, Santhome', type: 'school' },
    { name: 'Vidya Mandir Senior Secondary School, Mylapore', type: 'school' },
    { name: 'P.S. Senior Secondary School, Mylapore', type: 'school' },
    { name: 'SBOA School & Junior College, Anna Nagar', type: 'school' },
    { name: 'Chinmaya Vidyalaya, Anna Nagar', type: 'school' },
    { name: 'Don Bosco Higher Secondary School, Egmore', type: 'school' },
    { name: 'Loyola Matriculation Higher Secondary School, Kodambakkam', type: 'school' },
    { name: 'M. C. C. Higher Secondary School, Chetput', type: 'school' },
    { name: 'St. Patrick\'s Anglo Indian Higher Secondary School, Adyar', type: 'school' },
    { name: 'Kendriya Vidyalaya, IIT Madras', type: 'school' },
    { name: 'Kendriya Vidyalaya, CLRI Campus', type: 'school' },
    { name: 'Vana Vani Matriculation Higher Secondary School, IIT Campus', type: 'school' },
    { name: 'Aachi Global School', type: 'school' },
    { name: 'Asan Memorial Senior Secondary School, Thousand Lights', type: 'school' },
    { name: 'Babaji Vidhyashram, Sholinganallur', type: 'school' },
    { name: 'Bentinck School, Vepery', type: 'school' },
    { name: 'Bharath Senior Secondary School, Adyar', type: 'school' },
    { name: 'Chinmaya Vidyalaya, Virugambakkam', type: 'school' },
    { name: 'Campus K, Sholinganallur', type: 'school' },
    { name: 'Sri Ram Dayal Khemka Vivekananda Vidyalaya, Thiruvottiyur', type: 'school' },
    { name: 'Smt. Ramkuwar Devi Fomra Vivekananda Vidyalaya, Chromepet', type: 'school' },
    { name: 'Dr. Nalli Kuppuswami Vivekananda Vidyalaya, Korattur', type: 'school' },
    { name: 'C.S.I. Bain Matriculation Higher Secondary School, Kilpauk', type: 'school' },
    { name: 'C.S.I. Ewart Matriculation Higher Secondary School, Purasawalkam', type: 'school' },
    { name: 'Holy Angels Anglo Indian Higher Secondary School, T Nagar', type: 'school' },
    { name: 'KC High School, Kotturpuram', type: 'school' },
    { name: 'Khivraj Olympia School, Thiruneermalai', type: 'school' },
    { name: 'San Academy CBSE School, Pallikaranai', type: 'school' },
    { name: 'Kerala Vidhyalayam Higher Secondary School, Kilpauk', type: 'school' },
    { name: 'Maharishi Vidya Mandir, Chetput', type: 'school' },
    { name: 'MCTM International School, Chennai', type: 'school' },
    { name: 'Muslim Higher Secondary School, Triplicane', type: 'school' },
    { name: 'New Prince Matriculation Higher Secondary School, Adambakkam', type: 'school' },
    { name: 'St. Johns English School & Junior College, Besant Nagar', type: 'school' },
    { name: 'St. Joseph\'s Anglo-Indian Higher Secondary School, Perambur', type: 'school' },
    { name: 'St. Kevin\'s Anglo Indian High School, Royapuram', type: 'school' },
    { name: 'St. Mary\'s Anglo-Indian Higher Secondary School, Parry\'s Corner', type: 'school' },
    { name: 'St. Matthias Anglo Indian Higher Secondary School, Vepery', type: 'school' },
    { name: 'St. Theresa\'s Girls\' Higher Secondary School, Pallavaram', type: 'school' },
    { name: 'Sundravalli Memorial School, Chromepet', type: 'school' },
    { name: 'The Hindu Higher Secondary School, Triplicane', type: 'school' },
    { name: 'Unity Public School, Kotturpuram', type: 'school' },
    { name: 'Velammal New-Gen School, Surapet', type: 'school' },
    { name: 'Zion Matriculation Higher Secondary School, Selaiyur', type: 'school' },
    { name: 'Alpha School, CIT Nagar', type: 'school' },
    { name: 'Alwin Memorial Public School, Selaiyur', type: 'school' },
    { name: 'B.M.S. School, Mylapore', type: 'school' },
    { name: 'Hindu Senior Secondary School, Indira Nagar', type: 'school' },
    { name: 'Jawahar Vidyalaya, Ashok Nagar', type: 'school' },
    { name: 'Saraswathi Vidyalaya Senior Secondary School, Vadapalani', type: 'school' },
    { name: 'Sharanalaya Montessori School, Nungambakkam', type: 'school' },
    { name: 'Siragu Montessori School, Avadi', type: 'school' },
    { name: 'Sri Sankara Senior Secondary School, Adyar', type: 'school' },
    { name: 'Valliammal Matriculation Higher Secondary School, Chennai', type: 'school' },
    { name: 'Vedanta Academy, Vanagaram', type: 'school' },
    { name: 'Government Higher Secondary School, Adyar', type: 'school' },
    { name: 'Government Higher Secondary School, Ashok Nagar', type: 'school' },
    { name: 'Government Higher Secondary School, Kodambakkam', type: 'school' },
    { name: 'Government Higher Secondary School, T Nagar', type: 'school' },
    { name: 'Government Higher Secondary School, Velachery', type: 'school' },
    { name: 'Rosily Matriculation Higher Secondary School, Chromepet', type: 'school' },
    { name: 'N.S.N Memorial Senior Secondary School, Chromepet', type: 'school' },
    { name: 'La Chatelaine Junior College, Alwarthirunagar', type: 'school' },
    { name: 'Chintadripet Boys Higher Secondary School', type: 'school' },
    { name: 'Guru Nanak Matriculation School, Velachery', type: 'school' },
    { name: 'K.C.Sankaralinga Nadar Higher Secondary School, Old Washermanpet', type: 'school' },
    { name: 'AMM Matriculation Higher Secondary School, Kotturpuram', type: 'school' },
    { name: 'Good Earth School, Manimangalam', type: 'school' },
    { name: 'HLC International, Old Mahabalipuram Road', type: 'school' },
    { name: 'Kalaimagal Viddyalaya Matriculation Higher Secondary School, Royapuram', type: 'school' },
    { name: 'St. Columban\'s Girls Anglo-Indian Higher Secondary School, Parry\'s Corner', type: 'school' },
    { name: 'MCC Public School, Chetput', type: 'school' },
    { name: 'RMK Residential School, Kavaraipettai', type: 'school' },
    { name: 'Good Shepherd Convent Higher Secondary School, Nungambakkam', type: 'school' }
  ],
  'Coimbatore': [
    { name: 'PSG College of Technology', type: 'college' },
    { name: 'Coimbatore Institute of Technology (CIT)', type: 'college' },
    { name: 'Government College of Technology (GCT)', type: 'college' },
    { name: 'Amrita Vishwa Vidyapeetham', type: 'college' },
    { name: 'Karunya Institute of Technology', type: 'college' },
    { name: 'Kumaraguru College of Technology', type: 'college' },
    { name: 'Government Medical College, Coimbatore', type: 'college' },
    { name: 'Bharathiar University', type: 'college' },
    { name: 'Tamil Nadu Agricultural University (TNAU)', type: 'college' },
    { name: 'Nirmala College for Women', type: 'college' },
    { name: 'PSGR Krishnammal College', type: 'college' },
    { name: 'Sri Krishna College of Engineering', type: 'college' },
    { name: 'Hindusthan College of Arts and Science', type: 'college' },
    { name: 'Karpagam Academy of Higher Education', type: 'college' },
    { name: 'Stanes Higher Secondary School', type: 'school' },
    { name: 'KV Coimbatore', type: 'school' },
    { name: 'Chinmaya Vidyalaya, Coimbatore', type: 'school' },
    { name: 'Lisieux Matriculation School', type: 'school' },
    { name: 'G.D. Naidu Matriculation School', type: 'school' },
    { name: 'Perks Public School', type: 'school' }
  ],
  'Cuddalore': [
    { name: 'Annamalai University', type: 'college' },
    { name: 'Government Arts College, Cuddalore', type: 'college' },
    { name: 'Periyar Arts and Science College', type: 'college' },
    { name: 'St. Joseph\'s College, Cuddalore', type: 'college' },
    { name: 'Government Medical College, Chidambaram', type: 'college' },
    { name: 'MRK Institute of Technology', type: 'college' },
    { name: 'CK College of Engineering', type: 'college' },
    { name: 'Government Polytechnic College, Cuddalore', type: 'college' },
    { name: 'Jawahar Science College, Neyveli', type: 'college' },
    { name: 'St. Anne\'s College of Engineering', type: 'college' },
    { name: 'St. Mary\'s Matriculation School, Cuddalore', type: 'school' },
    { name: 'Government Higher Secondary School, Chidambaram', type: 'school' },
    { name: 'ARLM Higher Secondary School', type: 'school' },
    { name: 'NLC Higher Secondary School, Neyveli', type: 'school' },
    { name: 'Jawahar Matriculation School, Neyveli', type: 'school' },
    { name: 'Sacred Heart Higher Secondary School', type: 'school' }
  ],
  'Dharmapuri': [
    { name: 'Government Medical College, Dharmapuri', type: 'college' },
    { name: 'Government Arts College, Dharmapuri', type: 'college' },
    { name: 'Government Polytechnic College, Dharmapuri', type: 'college' },
    { name: 'Government Engineering College, Dharmapuri', type: 'college' },
    { name: 'Sapthagiri College of Engineering', type: 'college' },
    { name: 'Pachamuthu College of Arts and Science', type: 'college' },
    { name: 'Jai Sriram College of Arts and Science', type: 'college' },
    { name: 'Government Higher Secondary School, Dharmapuri', type: 'school' },
    { name: 'Loyola Matriculation School, Dharmapuri', type: 'school' },
    { name: 'Senthil Matriculation School', type: 'school' },
    { name: 'Vijay Vidyalaya School', type: 'school' },
    { name: 'Matric Higher Secondary School, Dharmapuri', type: 'school' },
    { name: 'St. Joseph\'s Matriculation School', type: 'school' }
  ],
  'Dindigul': [
    { name: 'Gandhigram Rural Institute', type: 'college' },
    { name: 'PSNA College of Engineering', type: 'college' },
    { name: 'Government Arts College, Dindigul', type: 'college' },
    { name: 'Government Polytechnic College, Dindigul', type: 'college' },
    { name: 'GTN Arts College', type: 'college' },
    { name: 'MVM Government Arts College for Women', type: 'college' },
    { name: 'SSM Institute of Engineering', type: 'college' },
    { name: 'RVS College of Engineering', type: 'college' },
    { name: 'St. Mary\'s Higher Secondary School, Dindigul', type: 'school' },
    { name: 'Dudley Higher Secondary School', type: 'school' },
    { name: 'MSP Solai Nadar School', type: 'school' },
    { name: 'Palani Andavar College (Palani)', type: 'college' },
    { name: 'Kodaikanal Christian College', type: 'college' },
    { name: 'Presentation Convent School, Kodaikanal', type: 'school' }
  ],
  'Erode': [
    { name: 'Kongu Engineering College', type: 'college' },
    { name: 'Bannari Amman Institute of Technology', type: 'college' },
    { name: 'Velalar College of Engineering', type: 'college' },
    { name: 'Government Arts and Science College, Erode', type: 'college' },
    { name: 'Erode Sengunthar Engineering College', type: 'college' },
    { name: 'Nandha Engineering College', type: 'college' },
    { name: 'Vellalar College for Women', type: 'college' },
    { name: 'Government Medical College, Erode (Perundurai)', type: 'college' },
    { name: 'Surya Engineering College', type: 'college' },
    { name: 'Railway School, Erode', type: 'school' },
    { name: 'Kalaimagal Matriculation School', type: 'school' },
    { name: 'BVB School, Erode', type: 'school' },
    { name: 'CSI Boys Higher Secondary School', type: 'school' },
    { name: 'Ideal Higher Secondary School', type: 'school' }
  ],
  'Kallakurichi': [
    { name: 'Government Medical College, Kallakurichi', type: 'college' },
    { name: 'Government Arts and Science College, Kallakurichi', type: 'college' },
    { name: 'AKT Memorial College of Engineering', type: 'college' },
    { name: 'Idhaya Engineering College for Women', type: 'college' },
    { name: 'TSM Jain College of Technology', type: 'college' },
    { name: 'Dr. R.K. Shanmugam College of Arts and Science', type: 'college' },
    { name: 'Sri Lakshmi College of Arts and Science', type: 'college' },
    { name: 'Muruga Polytechnic College', type: 'college' },
    { name: 'Government Higher Secondary School, Kallakurichi', type: 'school' },
    { name: 'AKT Academy School', type: 'school' },
    { name: 'Bharathi Matriculation School', type: 'school' },
    { name: 'Evergreen Matriculation School', type: 'school' },
    { name: 'St. Anthony\'s Matriculation School', type: 'school' }
  ],
  'Kanchipuram': [
    { name: 'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya (SCSVMV), Enathur', type: 'college' },
    { name: 'Pachaiyappa\'s College for Men, Kanchipuram', type: 'college' },
    { name: 'Pachaiyappa\'s College for Women, Kanchipuram', type: 'college' },
    { name: 'Arignar Anna Government Arts College, Kanchipuram', type: 'college' },
    { name: 'Kanchi Shri Krishna College of Arts and Science, Kilambi', type: 'college' },
    { name: 'Lord Venkateswara Engineering College, Kanchipuram', type: 'college' },
    { name: 'Pallavan College of Engineering, Kanchipuram', type: 'college' },
    { name: 'Adhi College of Engineering and Technology, Kanchipuram', type: 'college' },
    { name: 'Bhaktavatsalam Polytechnic College, Kanchipuram', type: 'college' },
    { name: 'Government ITI, Kanchipuram', type: 'college' },
    { name: 'Venkateswara College of Engineering (SVCE), Sriperumbudur', type: 'college' },
    { name: 'Rajiv Gandhi National Institute of Youth Development, Sriperumbudur', type: 'college' },
    { name: 'Jeppiaar Institute of Technology, Sriperumbudur', type: 'college' },
    { name: 'SMK Fomra Institute of Technology, Thaiyur', type: 'college' },
    { name: 'Rajalakshmi Engineering College, Thandalam', type: 'college' },
    { name: 'Saveetha Engineering College, Thandalam', type: 'college' },
    { name: 'Saveetha Medical College, Thandalam', type: 'college' },
    { name: 'Meenakshi Medical College Hospital and Research Institute, Enathur', type: 'college' },
    { name: 'Thiruvalluvar University Constituent College, Kanchipuram', type: 'college' },
    { name: 'Sri Muthukumaran Institute of Technology, Chikkarayapuram', type: 'college' },
    { name: 'Apollo Engineering College, Beemanthangal', type: 'college' },
    { name: 'Loyola Institute of Technology, Palanchur', type: 'college' },
    { name: 'DMI College of Engineering, Palanchur', type: 'college' },
    { name: 'Sri Sankara Arts and Science College, Enathur', type: 'college' },
    { name: 'Pallavan Polytechnic College, Kanchipuram', type: 'college' },
    { name: 'Arulmigu Meenakshi Amman College of Engineering, Vadamangalam', type: 'college' },
    { name: 'Lord Ayyappa Institute of Engineering and Technology, Walajabad', type: 'college' },
    { name: 'Kings Engineering College, Sriperumbudur', type: 'college' },
    { name: 'Sakthi Mariamman Engineering College, Sriperumbudur', type: 'college' },
    { name: 'Kanchi Heritage Arts and Science College for Women, Kanchipuram', type: 'college' },
    { name: 'St. Joseph\'s Matriculation Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Anderson Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Annie Besant Matriculation Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Sangford Schools, Kanchipuram', type: 'school' },
    { name: 'Maharishi Vidya Mandir, Kanchipuram', type: 'school' },
    { name: 'Olive Public School, Kanchipuram', type: 'school' },
    { name: 'Sri Ramakrishna Matriculation Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'MLM Matriculation Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Bhaktavatsalam Memorial School, Kanchipuram', type: 'school' },
    { name: 'Government Girls Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Government Boys Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Sacred Heart Matriculation Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Subbaraya Mudaliar Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'Infan Jesus Matriculation Higher Secondary School, Kanchipuram', type: 'school' },
    { name: 'St. Joseph\'s Residential School, Sriperumbudur', type: 'school' },
    { name: 'Maharishi International Residential School, Sriperumbudur', type: 'school' },
    { name: 'Spartan Iconic School, Sriperumbudur', type: 'school' },
    { name: 'Christ Matriculation Higher Secondary School, Sriperumbudur', type: 'school' },
    { name: 'Thriveni Academy, Oragadam', type: 'school' },
    { name: 'Hiranandani Parks School, Oragadam', type: 'school' },
    { name: 'Peace on Green Earth Public School, Kundrathur', type: 'school' },
    { name: 'Sivanthi Matriculation Higher Secondary School, Kundrathur', type: 'school' },
    { name: 'Little Flower Matriculation Higher Secondary School, Kundrathur', type: 'school' },
    { name: 'Government Higher Secondary School, Walajabad', type: 'school' },
    { name: 'Agurchand Manmull Jain School, Walajabad', type: 'school' },
    { name: 'Sunbeam School, Kanchipuram', type: 'school' },
    { name: 'Seventh Day Adventist School, Kanchipuram', type: 'school' },
    { name: 'Heritage School, Kanchipuram', type: 'school' },
    { name: 'Amrita Vidyalayam, Kanchipuram', type: 'school' },
    { name: 'Ponvidya Mandir, Kanchipuram', type: 'school' }
  ],
  'Kanyakumari': [
    { name: 'Scott Christian College', type: 'college' },
    { name: 'South Travancore Hindu College', type: 'college' },
    { name: 'Holy Cross College, Nagercoil', type: 'college' },
    { name: 'Kanyakumari Government Medical College', type: 'college' },
    { name: 'Noorul Islam University', type: 'college' },
    { name: 'St. Jude\'s College', type: 'college' },
    { name: 'Government Engineering College, Nagercoil', type: 'college' },
    { name: 'Marian College of Arts and Science', type: 'college' },
    { name: 'Sun College of Engineering', type: 'college' },
    { name: 'St. Xavier\'s Catholic College of Engineering', type: 'college' },
    { name: 'S.L.B. School, Nagercoil', type: 'school' },
    { name: 'DVD Higher Secondary School', type: 'school' },
    { name: 'St. Joseph\'s School, Nagercoil', type: 'school' },
    { name: 'Little Flower School, Nagercoil', type: 'school' },
    { name: 'Holy Family School, Nagercoil', type: 'school' }
  ],
  'Karur': [
    { name: 'Government Medical College, Karur', type: 'college' },
    { name: 'Government Arts College, Karur', type: 'college' },
    { name: 'M. Kumarasamy College of Engineering', type: 'college' },
    { name: 'VSB Engineering College', type: 'college' },
    { name: 'Karur College of Engineering', type: 'college' },
    { name: 'Government Polytechnic College, Karur', type: 'college' },
    { name: 'N.S.H.M. School, Karur', type: 'school' },
    { name: 'Government Higher Secondary School, Karur', type: 'school' },
    { name: 'Vidhya Mandir School, Karur', type: 'school' },
    { name: 'Cheran Matriculation School', type: 'school' },
    { name: 'Pasupatheeswarar School', type: 'school' },
    { name: 'Kongu Matriculation School', type: 'school' }
  ],
  'Krishnagiri': [
    { name: 'Adhiyamaan College of Engineering, Hosur', type: 'college' },
    { name: 'Government Engineering College, Bargur', type: 'college' },
    { name: 'Government Arts College, Krishnagiri', type: 'college' },
    { name: 'Government Polytechnic College, Krishnagiri', type: 'college' },
    { name: 'Government Medical College, Krishnagiri', type: 'college' },
    { name: 'Hosur Arts and Science College', type: 'college' },
    { name: 'M.G.R. College of Arts and Science, Hosur', type: 'college' },
    { name: 'Government Higher Secondary School, Krishnagiri', type: 'school' },
    { name: 'St. John\'s School, Hosur', type: 'school' },
    { name: 'TVEC School, Hosur', type: 'school' },
    { name: 'Vijay Vidyalaya School, Krishnagiri', type: 'school' },
    { name: 'Parimalam School, Hosur', type: 'school' },
    { name: 'Brindhavan School, Krishnagiri', type: 'school' }
  ],
  'Madurai': [
    { name: 'Thiagarajar College of Engineering (TCE)', type: 'college' },
    { name: 'Madurai Kamaraj University', type: 'college' },
    { name: 'Madura College', type: 'college' },
    { name: 'American College, Madurai', type: 'college' },
    { name: 'Lady Doak College', type: 'college' },
    { name: 'Fatima College', type: 'college' },
    { name: 'Thiagarajar College', type: 'college' },
    { name: 'Madurai Medical College', type: 'college' },
    { name: 'Velammal College of Engineering', type: 'college' },
    { name: 'Womens Christian College, Madurai', type: 'college' },
    { name: 'SVN College, Madurai', type: 'college' },
    { name: 'Government Polytechnic College, Madurai', type: 'college' },
    { name: 'St. Mary\'s Higher Secondary School', type: 'school' },
    { name: 'Madura College Higher Secondary School', type: 'school' },
    { name: 'TV Sundaram Higher Secondary School', type: 'school' },
    { name: 'Mahatma School, Madurai', type: 'school' },
    { name: 'KV Madurai (PTC)', type: 'school' },
    { name: 'Noyes Higher Secondary School', type: 'school' },
    { name: 'OCPM Girls Higher Secondary School', type: 'school' }
  ],
  'Mayiladuthurai': [
    { name: 'A.V.C. College (Autonomous), Mannampandal', type: 'college' },
    { name: 'Dharmapuram Adhinam Arts College', type: 'college' },
    { name: 'Dharmapuram Gnanambigai Government Arts College for Women', type: 'college' },
    { name: 'Poompuhar College, Melaiyur', type: 'college' },
    { name: 'TBML College, Poraiyar', type: 'college' },
    { name: 'Government Arts and Science College, Manalmedu', type: 'college' },
    { name: 'Vivekananda College of Arts & Science for Women', type: 'college' },
    { name: 'ARC Viswanathan College of Arts & Science', type: 'college' },
    { name: 'Kalaimagal Arts & Science College', type: 'college' },
    { name: 'A.V.C. College of Engineering', type: 'college' },
    { name: 'A.V.C. Polytechnic College', type: 'college' },
    { name: 'Srinivasa Subbaraya Government Polytechnic College', type: 'college' },
    { name: 'Government Industrial Training Institute (ITI), Mayiladuthurai', type: 'college' },
    { name: 'St. Paul Higher Secondary School, Mayiladuthurai', type: 'school' },
    { name: 'DBTR National Higher Secondary School, Mayiladuthurai', type: 'school' },
    { name: 'Sacred Heart Higher Secondary School', type: 'school' },
    { name: 'Best Matriculation Higher Secondary School, Sirkali', type: 'school' },
    { name: 'Sirkali Government Boys Higher Secondary School', type: 'school' },
    { name: 'Gurugyan Matric Higher Secondary School', type: 'school' },
    { name: 'Sembanarkoil Government Higher Secondary School', type: 'school' }
  ],
  'Nagapattinam': [
    { name: 'Government Arts and Science College, Nagapattinam', type: 'college' },
    { name: 'Valivalam Desikar Polytechnic College', type: 'college' },
    { name: 'Government Medical College, Nagapattinam', type: 'college' },
    { name: 'E.G.S. Pillay Engineering College', type: 'college' },
    { name: 'ADJ Dharmambal Polytechnic College', type: 'college' },
    { name: 'Netaji Subash Chandra Bose College', type: 'college' },
    { name: 'Nagore Modern School', type: 'school' },
    { name: 'CSM Higher Secondary School', type: 'school' },
    { name: 'National School, Nagapattinam', type: 'school' },
    { name: 'Vedaranyam Government Higher Secondary School', type: 'school' },
    { name: 'St. Anthonys Matriculation School', type: 'school' },
    { name: 'St. Johns School, Nagapattinam', type: 'school' }
  ],
  'Namakkal': [
    { name: 'Government Medical College, Namakkal', type: 'college' },
    { name: 'Government Arts College, Namakkal', type: 'college' },
    { name: 'Vivekananda College of Engineering for Women', type: 'college' },
    { name: 'Mahendra Engineering College', type: 'college' },
    { name: 'Gnanamani College of Technology', type: 'college' },
    { name: 'Selvam College of Technology', type: 'college' },
    { name: 'Paavai Engineering College', type: 'college' },
    { name: 'K.S. Rangasamy College of Technology', type: 'college' },
    { name: 'Mahendra Institute of Technology', type: 'college' },
    { name: 'Government Higher Secondary School, Namakkal', type: 'school' },
    { name: 'Santhosh Vidyalaya School', type: 'school' },
    { name: 'SPK Matriculation School', type: 'school' },
    { name: 'Trinity Academy School', type: 'school' },
    { name: 'Vidhya Vikas School, Tiruchengode', type: 'school' },
    { name: 'Namakkal South Government High School', type: 'school' }
  ],
  'Nilgiris': [
    { name: 'Government Arts College, Ooty', type: 'college' },
    { name: 'Government Polytechnic College, Ooty', type: 'college' },
    { name: 'JSS College of Pharmacy', type: 'college' },
    { name: 'Government Medical College, Ooty', type: 'college' },
    { name: 'CSI College of Engineering, Ketti', type: 'college' },
    { name: 'Lawrence School, Lovedale', type: 'school' },
    { name: 'Breeks Memorial School', type: 'school' },
    { name: 'St. Joseph\'s Higher Secondary School, Coonoor', type: 'school' },
    { name: 'Kotagiri Government Higher Secondary School', type: 'school' },
    { name: 'Kendriya Vidyalaya Aruvankadu', type: 'school' },
    { name: 'St. Hildas Matriculation School', type: 'school' },
    { name: 'Hebron School, Ooty', type: 'school' }
  ],
  'Perambalur': [
    { name: 'Government Arts and Science College, Perambalur', type: 'college' },
    { name: 'Dhanalakshmi Srinivasan Engineering College', type: 'college' },
    { name: 'Srinivasan Engineering College', type: 'college' },
    { name: 'Roever Engineering College', type: 'college' },
    { name: 'Government Polytechnic College, Perambalur', type: 'college' },
    { name: 'Thanthai Roever Arts and Science College', type: 'college' },
    { name: 'Government Higher Secondary School, Perambalur', type: 'school' },
    { name: 'Golden Gates School', type: 'school' },
    { name: 'Eden Garden School', type: 'school' },
    { name: 'Thantai Hans Roever School', type: 'school' },
    { name: 'St. Johns High School, Perambalur', type: 'school' },
    { name: 'Government School, Veppanthattai', type: 'school' }
  ],
  'Pudukkottai': [
    { name: 'H.H. The Rajah\'s College', type: 'college' },
    { name: 'Government Medical College, Pudukkottai', type: 'college' },
    { name: 'JJ College of Arts and Science', type: 'college' },
    { name: 'Government Arts College for Women', type: 'college' },
    { name: 'Mount Zion College of Engineering', type: 'college' },
    { name: 'Government Polytechnic College, Pudukkottai', type: 'college' },
    { name: 'Shanmugha Engineering College', type: 'college' },
    { name: 'MNSK College of Engineering', type: 'college' },
    { name: 'Government Higher Secondary School, Pudukkottai', type: 'school' },
    { name: 'St. Mary\'s School, Pudukkottai', type: 'school' },
    { name: 'Vairam Higher Secondary School', type: 'school' },
    { name: 'Sri Venkateswara School', type: 'school' },
    { name: 'Montfort Higher Secondary School', type: 'school' }
  ],
  'Ramanathapuram': [
    { name: 'Government Medical College, Ramanathapuram', type: 'college' },
    { name: 'Government Arts College, Ramanathapuram', type: 'college' },
    { name: 'Government Engineering College, Ramanathapuram', type: 'college' },
    { name: 'Thassim Beevi Abdul Kader College for Women', type: 'college' },
    { name: 'Mohamed Sathak Engineering College', type: 'college' },
    { name: 'Syed Hameedha Arts and Science College', type: 'college' },
    { name: 'Government Polytechnic College, Ramanathapuram', type: 'college' },
    { name: 'Government Higher Secondary School, Ramanathapuram', type: 'school' },
    { name: 'Schwartz Higher Secondary School', type: 'school' },
    { name: 'St. Andrew\'s School', type: 'school' },
    { name: 'Velumanickam School', type: 'school' },
    { name: 'Kadaladi Government High School', type: 'school' },
    { name: 'CSI School, Ramanathapuram', type: 'school' }
  ],
  'Ranipet': [
    { name: 'C. Abdul Hakeem College of Engineering & Technology, Melvisharam', type: 'college' },
    { name: 'Ranippettai Engineering College, Walajapet', type: 'college' },
    { name: 'Arignar Anna Government Arts & Science College for Women, Walajapet', type: 'college' },
    { name: 'Global Institute of Engineering and Technology, Melvisharam', type: 'college' },
    { name: 'Arcot Sri Mahalakshmi Women\'s College of Education, Arcot', type: 'college' },
    { name: 'Global College of Arts and Science for Women', type: 'college' },
    { name: 'Government Medical College, Ranipet', type: 'college' },
    { name: 'Government Arts and Science College, Arakkonam', type: 'college' },
    { name: 'Adhiparasakthi Engineering College', type: 'college' },
    { name: 'Government Higher Secondary School, Ranipet', type: 'school' },
    { name: 'BHEL School, Ranipet', type: 'school' },
    { name: 'Shanthi Sagar School', type: 'school' },
    { name: 'Little Flower School, Ranipet', type: 'school' },
    { name: 'Vellayan Matriculation School', type: 'school' }
  ],
  'Salem': [
    { name: 'Government College of Engineering, Salem', type: 'college' },
    { name: 'Sona College of Technology', type: 'college' },
    { name: 'Vinayaka Missions University', type: 'college' },
    { name: 'Periyar University', type: 'college' },
    { name: 'Salem Government Medical College', type: 'college' },
    { name: 'Government Arts College, Salem', type: 'college' },
    { name: 'Government Polytechnic College, Salem', type: 'college' },
    { name: 'Salem Sowdeswari College', type: 'college' },
    { name: 'Dhirajlal Gandhi College of Technology', type: 'college' },
    { name: 'AVS College of Arts and Science', type: 'college' },
    { name: 'Holy Cross School, Salem', type: 'school' },
    { name: 'St. Mary\'s School, Salem', type: 'school' },
    { name: 'KV Salem', type: 'school' },
    { name: 'Golden Gates Matriculation School', type: 'school' },
    { name: 'Cluny Higher Secondary School', type: 'school' },
    { name: 'Little Flower Higher Secondary School', type: 'school' },
    { name: 'Gugai Government Girls High School', type: 'school' }
  ],
  'Sivagangai': [
    { name: 'Alagappa University', type: 'college' },
    { name: 'Alagappa Government Arts College', type: 'college' },
    { name: 'Government Medical College, Sivagangai', type: 'college' },
    { name: 'Raja Doraisingam Government Arts College', type: 'college' },
    { name: 'KLN College of Engineering', type: 'college' },
    { name: 'Central Electro Chemical Research Institute (CECRI)', type: 'college' },
    { name: 'Ananda College, Devakottai', type: 'college' },
    { name: 'Seethalakshmi Achi College for Women', type: 'college' },
    { name: 'Government Higher Secondary School, Sivagangai', type: 'school' },
    { name: 'Kambar Higher Secondary School', type: 'school' },
    { name: 'St. Joseph\'s School, Sivagangai', type: 'school' },
    { name: 'Annamalai School, Karaikudi', type: 'school' },
    { name: 'Subbiah School, Karaikudi', type: 'school' },
    { name: 'Devakottai Government High School', type: 'school' }
  ],
  'Tenkasi': [
    { name: 'Government Arts and Science College, Tenkasi', type: 'college' },
    { name: 'Government Medical College, Tenkasi', type: 'college' },
    { name: 'JP College of Engineering', type: 'college' },
    { name: 'ICL Engineering College', type: 'college' },
    { name: 'Government Polytechnic College, Tenkasi', type: 'college' },
    { name: 'St. John\'s College of Arts and Science', type: 'college' },
    { name: 'Government Higher Secondary School, Tenkasi', type: 'school' },
    { name: 'Eicher Higher Secondary School', type: 'school' },
    { name: 'MKNH School, Tenkasi', type: 'school' },
    { name: 'Little Flower School, Tenkasi', type: 'school' },
    { name: 'Pavoorchatram High School', type: 'school' },
    { name: 'Sankarankovil Government School', type: 'school' }
  ],
  'Thanjavur': [
    { name: 'SASTRA Deemed University', type: 'college' },
    { name: 'Thanjavur Medical College', type: 'college' },
    { name: 'Tamil University', type: 'college' },
    { name: 'Rajah Serfoji Government Arts College', type: 'college' },
    { name: 'Government College of Engineering, Thanjavur', type: 'college' },
    { name: 'Kumbakonam Government Arts College', type: 'college' },
    { name: 'Periyar Maniammai University', type: 'college' },
    { name: 'Kumbakonam Government Medical College', type: 'college' },
    { name: 'St. Peter\'s Higher Secondary School', type: 'school' },
    { name: 'Kalyanasundaram School', type: 'school' },
    { name: 'Sacret Heart School, Thanjavur', type: 'school' },
    { name: 'KV Thanjavur', type: 'school' },
    { name: 'Maxwell Higher Secondary School', type: 'school' },
    { name: 'Banadurai High School, Kumbakonam', type: 'school' }
  ],
  'Theni': [
    { name: 'Theni Medical College', type: 'college' },
    { name: 'Government Arts and Science College, Theni', type: 'college' },
    { name: 'Bharath Niketan Engineering College', type: 'college' },
    { name: 'Theni Kammavar Sangam College of Tech', type: 'college' },
    { name: 'Government Engineering College, Bodinayakanur', type: 'college' },
    { name: 'Hajee Karutha Rowther Howdia College', type: 'college' },
    { name: 'Government Higher Secondary School, Theni', type: 'school' },
    { name: 'Nadar Saraswathi School', type: 'school' },
    { name: 'Velammal Bodhi Campus, Theni', type: 'school' },
    { name: 'Mary Matha School, Theni', type: 'school' },
    { name: 'Chinnamanur Government High School', type: 'school' },
    { name: 'Cumbum Government School', type: 'school' }
  ],
  'Thoothukudi': [
    { name: 'V.O. Chidambaram College', type: 'college' },
    { name: 'St. Mary\'s College, Thoothukudi', type: 'college' },
    { name: 'Government Medical College, Thoothukudi', type: 'college' },
    { name: 'APC Mahalakshmi College for Women', type: 'college' },
    { name: 'Government Polytechnic College, Thoothukudi', type: 'college' },
    { name: 'Kamaraj College', type: 'college' },
    { name: 'Holy Cross Home Science College', type: 'college' },
    { name: 'St. Thomas School', type: 'school' },
    { name: 'BMC Higher Secondary School', type: 'school' },
    { name: 'Holy Cross School, Thoothukudi', type: 'school' },
    { name: 'KV Thoothukudi', type: 'school' },
    { name: 'Geetha Higher Secondary School', type: 'school' },
    { name: 'CSI School, Thoothukudi', type: 'school' }
  ],
  'Tiruchirappalli': [
    { name: 'National Institute of Technology (NIT Trichy)', type: 'college' },
    { name: 'St. Joseph\'s College, Trichy', type: 'college' },
    { name: 'Bishop Heber College', type: 'college' },
    { name: 'Jamal Mohamed College', type: 'college' },
    { name: 'National College, Trichy', type: 'college' },
    { name: 'Holy Cross College, Trichy', type: 'college' },
    { name: 'Urumu Dhanalakshmi College', type: 'college' },
    { name: 'Srimad Andavan College', type: 'college' },
    { name: 'Government Medical College, Trichy', type: 'college' },
    { name: 'Tiruchirappalli Engineering College', type: 'college' },
    { name: 'K. Ramakrishnan College of Technology', type: 'college' },
    { name: 'M.A.M. College of Engineering', type: 'college' },
    { name: 'Campion Higher Secondary School', type: 'school' },
    { name: 'St. Joseph\'s Higher Secondary School, Trichy', type: 'school' },
    { name: 'KV Trichy (No. 1 & No. 2)', type: 'school' },
    { name: 'RSK Higher Secondary School', type: 'school' },
    { name: 'Montfort Higher Secondary School, Trichy', type: 'school' },
    { name: 'SBIOA Public School, Trichy', type: 'school' },
    { name: 'BHEL School, Trichy', type: 'school' }
  ],
  'Tirunelveli': [
    { name: 'St. Xavier\'s College, Palayamkottai', type: 'college' },
    { name: 'St. John\'s College, Palayamkottai', type: 'college' },
    { name: 'Government College of Engineering, Tirunelveli', type: 'college' },
    { name: 'Tirunelveli Medical College', type: 'college' },
    { name: 'Sarah Tucker College', type: 'college' },
    { name: 'Sadakathullah Appa College', type: 'college' },
    { name: 'Francis Xavier Engineering College', type: 'college' },
    { name: 'Einstein College of Engineering', type: 'college' },
    { name: 'MDT Hindu College', type: 'college' },
    { name: 'St. Ignatius Convent Higher Secondary School', type: 'school' },
    { name: 'Schaffter Higher Secondary School', type: 'school' },
    { name: 'Bell Matriculation School', type: 'school' },
    { name: 'KV Tirunelveli', type: 'school' },
    { name: 'St. Johns School, Tirunelveli', type: 'school' }
  ],
  'Tirupathur': [
    { name: 'Sacred Heart College (Autonomous), Tirupattur', type: 'college' },
    { name: 'Marudhar Kesari Jain College for Women, Vaniyambadi', type: 'college' },
    { name: 'Islamiah Women\'s Arts and Science College, Vaniyambadi', type: 'college' },
    { name: 'Sri Nandhanam College of Engineering and Technology', type: 'college' },
    { name: 'Government Arts and Science College, Tirupattur', type: 'college' },
    { name: 'Bharathidasan Engineering College, Natarampalli', type: 'college' },
    { name: 'Government Polytechnic College, Tirupathur', type: 'college' },
    { name: 'Government Higher Secondary School, Tirupathur', type: 'school' },
    { name: 'Don Bosco Matriculation School, Tirupathur', type: 'school' },
    { name: 'Meenakshi Matriculation School', type: 'school' },
    { name: 'Ambur Government High School', type: 'school' },
    { name: 'Vaniyambadi Boys School', type: 'school' }
  ],
  'Tiruppur': [
    { name: 'Government Arts and Science College, Tiruppur', type: 'college' },
    { name: 'Angel College of Engineering', type: 'college' },
    { name: 'Chikkanna Government Arts College', type: 'college' },
    { name: 'NIFT-TEA College of Knitwear Fashion', type: 'college' },
    { name: 'Professional Institute of Technology', type: 'college' },
    { name: 'Jai Sriram Engineering College', type: 'college' },
    { name: 'Government Medical College, Tiruppur', type: 'college' },
    { name: 'Government Higher Secondary School, Tiruppur', type: 'school' },
    { name: 'TEA Public School', type: 'school' },
    { name: 'Vivakalaya School, Tiruppur', type: 'school' },
    { name: 'Frontier Matriculation School', type: 'school' },
    { name: 'K.S.C. Government High School', type: 'school' },
    { name: 'Avinashi Government School', type: 'school' }
  ],
  'Tiruvallur': [
    { name: 'Poonamallee Government Arts College', type: 'college' },
    { name: 'RMK Engineering College', type: 'college' },
    { name: 'Prathyusha Engineering College', type: 'college' },
    { name: 'S.A. Engineering College', type: 'college' },
    { name: 'Vel Tech Rangarajan Dr. Sagunthala R&D', type: 'college' },
    { name: 'Government Medical College, Tiruvallur', type: 'college' },
    { name: 'LNR Institute of Technology', type: 'college' },
    { name: 'Sriram Engineering College', type: 'college' },
    { name: 'Government Higher Secondary School, Tiruvallur', type: 'school' },
    { name: 'Velammal Bodhi Campus, Ponneri', type: 'school' },
    { name: 'Sri Niketan Mat. School', type: 'school' },
    { name: 'Sethu Bhaskara School, Ambattur', type: 'school' },
    { name: 'Tiruttani Government School', type: 'school' },
    { name: 'Gummidipoondi Government High School', type: 'school' }
  ],
  'Tiruvannamalai': [
    { name: 'Arignar Anna Government Arts College', type: 'college' },
    { name: 'Government Medical College, Tiruvannamalai', type: 'college' },
    { name: 'SKP Engineering College', type: 'college' },
    { name: 'Arunai Engineering College', type: 'college' },
    { name: 'Shanmugha Arts and Science College', type: 'college' },
    { name: 'Kamban Engineering College', type: 'college' },
    { name: 'University College of Engineering', type: 'college' },
    { name: 'Government Higher Secondary School, Tiruvannamalai', type: 'school' },
    { name: 'Danish Mission School', type: 'school' },
    { name: 'Mount Saint Joseph School', type: 'school' },
    { name: 'Vignesh School, Tiruvannamalai', type: 'school' },
    { name: 'Polur Government High School', type: 'school' },
    { name: 'Chengam Government School', type: 'school' }
  ],
  'Tiruvarur': [
    { name: 'Central University of Tamil Nadu (CUTN)', type: 'college' },
    { name: 'Government Thiruvarur Medical College', type: 'college' },
    { name: 'Anjalai Ammal Mahalingam Engineering College (AAMEC)', type: 'college' },
    { name: 'Thiru-Vi-Ka Government Arts College, Tiruvarur', type: 'college' },
    { name: 'Sengamala Thayaar Educational Trust (STET) Women\'s College', type: 'college' },
    { name: 'Mannai Rajagopalaswamy Government Arts College', type: 'college' },
    { name: 'Rabiammal Ahamed Maideen College', type: 'college' },
    { name: 'Government Polytechnic College, Tiruvarur', type: 'college' },
    { name: 'Swami Dayananda College of Arts and Science', type: 'college' },
    { name: 'Tiruvarur Government Higher Secondary School', type: 'school' },
    { name: 'Veludayar Higher Secondary School', type: 'school' },
    { name: 'New Bharat Matriculation School', type: 'school' },
    { name: 'St. Johns School, Tiruvarur', type: 'school' }
  ],
  'Vellore': [
    { name: 'Vellore Institute of Technology (VIT)', type: 'college' },
    { name: 'Christian Medical College (CMC), Vellore', type: 'college' },
    { name: 'Government College of Engineering, Vellore', type: 'college' },
    { name: 'Voorhees College', type: 'college' },
    { name: 'Auxilium College', type: 'college' },
    { name: 'Muthurangam Government Arts College', type: 'college' },
    { name: 'DKM College for Women', type: 'college' },
    { name: 'Government Polytechnic College, Vellore', type: 'college' },
    { name: 'Idhaya Engineering College', type: 'college' },
    { name: 'C. Abdul Hakeem College (nearby but associated)', type: 'college' },
    { name: 'St. Mary\'s Higher Secondary School, Vellore', type: 'school' },
    { name: 'E.V.R. Nagammai Government Girls School', type: 'school' },
    { name: 'KV Vellore (Katpadi)', type: 'school' },
    { name: 'Holy Cross School, Vellore', type: 'school' },
    { name: 'Don Bosco School, Vellore', type: 'school' },
    { name: 'Gudiyatham Government School', type: 'school' },
    { name: 'LATH School, Vellore', type: 'school' }
  ],
  'Viluppuram': [
    { name: 'Government Medical College, Viluppuram', type: 'college' },
    { name: 'Government Arts and Science College, Viluppuram', type: 'college' },
    { name: 'Anna University (Regional Campus), Viluppuram', type: 'college' },
    { name: 'Theivanai Ammal College for Women', type: 'college' },
    { name: 'ES Engineering College', type: 'college' },
    { name: 'Government Polytechnic College, Viluppuram', type: 'college' },
    { name: 'IFET College of Engineering', type: 'college' },
    { name: 'Surya Group of Institutions', type: 'college' },
    { name: 'Government Higher Secondary School, Viluppuram', type: 'school' },
    { name: 'Sacred Heart Higher Secondary School', type: 'school' },
    { name: 'Ramakrishna Matriculation School', type: 'school' },
    { name: 'E.S. Matriculation School', type: 'school' },
    { name: 'Gingee Government School', type: 'school' },
    { name: 'V.R.P. School, Viluppuram', type: 'school' }
  ],
  'Virudhunagar': [
    { name: 'Government Medical College, Virudhunagar', type: 'college' },
    { name: 'VHNSN College', type: 'college' },
    { name: 'V.V. Vanniaperumal College for Women', type: 'college' },
    { name: 'Ayya Nadar Janaki Ammal College, Sivakasi', type: 'college' },
    { name: 'Mepco Schlenk Engineering College', type: 'college' },
    { name: 'Kalasalingam University', type: 'college' },
    { name: 'P.S.R. Engineering College', type: 'college' },
    { name: 'Kamaraj College of Engineering', type: 'college' },
    { name: 'V.H.N. Senthilkumara Nadar College', type: 'college' },
    { name: 'SHNV Higher Secondary School', type: 'school' },
    { name: 'Kshatriya Girls Higher Secondary School', type: 'school' },
    { name: 'Coronation Girls Higher Secondary School, Sivakasi', type: 'school' },
    { name: 'KVS School, Virudhunagar', type: 'school' },
    { name: 'Sivakasi Government School', type: 'school' },
    { name: 'Aruppukkottai Government High School', type: 'school' }
  ]
};

async function main() {
  try {
    console.log('--- Reseeding Institutions with MASSIVE REAL DATASET (550+ Entries) ---');
    
    // 1. Check if table exists
    await db.query('TRUNCATE TABLE institutions');
    console.log('Cleared existing institutions.');

    // 2. Prepare values
    const finalInstitutions = [];
    Object.entries(rawData).forEach(([district, items]) => {
      items.forEach(item => {
        finalInstitutions.push([
          item.name, 
          item.type, 
          district, 
          `${item.name}, ${district}, Tamil Nadu`, 
          `admin@${item.name.toLowerCase().replace(/[^a-z]/g, '')}.edu.in`
        ]);
      });
    });

    // 3. Insert
    await db.query(
      'INSERT INTO institutions (name, type, district, address, contact_email) VALUES ?',
      [finalInstitutions]
    );

    console.log(`✅ SUCCESS: Inserted ${finalInstitutions.length} real institutions across all 38 districts.`);
    process.exit(0);
  } catch (err) {
    console.error('❌ FAILED:', err);
    process.exit(1);
  }
}

main();
