INSERT INTO institutions (name, district, type) VALUES
('Government Arts College Ariyalur', 'Ariyalur', 'college'),
('Ariyalur Medical College', 'Ariyalur', 'college'),
('Ariyalur Engineering College', 'Ariyalur', 'college'),
('Vinayaga Arts and Science College Ariyalur', 'Ariyalur', 'college'),
('Meenakshi Ramasamy Arts and Science College Ariyalur', 'Ariyalur', 'college'),
('Modern Arts and Science College Ariyalur', 'Ariyalur', 'college'),
('Government Higher Secondary School Ariyalur', 'Ariyalur', 'school'),
('KV Ariyalur', 'Ariyalur', 'school'),
('PSBB School Ariyalur', 'Ariyalur', 'school'),
('DAV School Ariyalur', 'Ariyalur', 'school'),
('Don Bosco Ariyalur', 'Ariyalur', 'school'),
('St. Joseph's School Ariyalur', 'Ariyalur', 'school'),
('Holy Angels School Ariyalur', 'Ariyalur', 'school'),
('Sacred Heart School Ariyalur', 'Ariyalur', 'school'),
('Montfort School Ariyalur', 'Ariyalur', 'school'),
('Little Flower School Ariyalur', 'Ariyalur', 'school'),
('Government Arts College Chengalpattu', 'Chengalpattu', 'college'),
('Chengalpattu Medical College', 'Chengalpattu', 'college'),
('Chengalpattu Engineering College', 'Chengalpattu', 'college'),
('Vinayaga Arts and Science College Chengalpattu', 'Chengalpattu', 'college'),
('Meenakshi Ramasamy Arts and Science College Chengalpattu', 'Chengalpattu', 'college'),
('Modern Arts and Science College Chengalpattu', 'Chengalpattu', 'college'),
('Government Higher Secondary School Chengalpattu', 'Chengalpattu', 'school'),
('KV Chengalpattu', 'Chengalpattu', 'school'),
('PSBB School Chengalpattu', 'Chengalpattu', 'school'),
('DAV School Chengalpattu', 'Chengalpattu', 'school'),
('Don Bosco Chengalpattu', 'Chengalpattu', 'school'),
('St. Joseph's School Chengalpattu', 'Chengalpattu', 'school'),
('Holy Angels School Chengalpattu', 'Chengalpattu', 'school'),
('Sacred Heart School Chengalpattu', 'Chengalpattu', 'school'),
('Montfort School Chengalpattu', 'Chengalpattu', 'school'),
('Little Flower School Chengalpattu', 'Chengalpattu', 'school'),
('Loyola College', 'Chennai', 'college'),
('Madras Christian College', 'Chennai', 'college'),
('Presidency College', 'Chennai', 'college'),
('Ethiraj College for Women', 'Chennai', 'college'),
('Stella Maris College', 'Chennai', 'college'),
('Women's Christian College', 'Chennai', 'college'),
('IIT Madras', 'Chennai', 'college'),
('Anna University', 'Chennai', 'college'),
('Madras Medical College', 'Chennai', 'college'),
('Stanley Medical College', 'Chennai', 'college'),
('Government Higher Secondary School Chennai', 'Chennai', 'school'),
('KV Chennai', 'Chennai', 'school'),
('PSBB School Chennai', 'Chennai', 'school'),
('DAV School Chennai', 'Chennai', 'school'),
('Don Bosco Chennai', 'Chennai', 'school'),
('St. Joseph's School Chennai', 'Chennai', 'school'),
('Holy Angels School Chennai', 'Chennai', 'school'),
('Sacred Heart School Chennai', 'Chennai', 'school'),
('Montfort School Chennai', 'Chennai', 'school'),
('Little Flower School Chennai', 'Chennai', 'school'),
('PSG College of Technology', 'Coimbatore', 'college'),
('Coimbatore Institute of Technology', 'Coimbatore', 'college'),
('Government College of Technology', 'Coimbatore', 'college'),
('Amrita Vishwa Vidyapeetham', 'Coimbatore', 'college'),
('Karunya Institute of Technology', 'Coimbatore', 'college'),
('Kumaraguru College of Technology', 'Coimbatore', 'college'),
('Sri Krishna College of Engineering', 'Coimbatore', 'college'),
(' Nirmala College for Women', 'Coimbatore', 'college'),
('PSGR Krishnammal College for Women', 'Coimbatore', 'college'),
('Government Arts College Coimbatore', 'Coimbatore', 'college'),
('Government Higher Secondary School Coimbatore', 'Coimbatore', 'school'),
('KV Coimbatore', 'Coimbatore', 'school'),
('PSBB School Coimbatore', 'Coimbatore', 'school'),
('DAV School Coimbatore', 'Coimbatore', 'school'),
('Don Bosco Coimbatore', 'Coimbatore', 'school'),
('St. Joseph's School Coimbatore', 'Coimbatore', 'school'),
('Holy Angels School Coimbatore', 'Coimbatore', 'school'),
('Sacred Heart School Coimbatore', 'Coimbatore', 'school'),
('Montfort School Coimbatore', 'Coimbatore', 'school'),
('Little Flower School Coimbatore', 'Coimbatore', 'school'),
('Government Arts College Cuddalore', 'Cuddalore', 'college'),
('Cuddalore Medical College', 'Cuddalore', 'college'),
('Cuddalore Engineering College', 'Cuddalore', 'college'),
('Vinayaga Arts and Science College Cuddalore', 'Cuddalore', 'college'),
('Meenakshi Ramasamy Arts and Science College Cuddalore', 'Cuddalore', 'college'),
('Modern Arts and Science College Cuddalore', 'Cuddalore', 'college'),
('Government Higher Secondary School Cuddalore', 'Cuddalore', 'school'),
('KV Cuddalore', 'Cuddalore', 'school'),
('PSBB School Cuddalore', 'Cuddalore', 'school'),
('DAV School Cuddalore', 'Cuddalore', 'school'),
('Don Bosco Cuddalore', 'Cuddalore', 'school'),
('St. Joseph's School Cuddalore', 'Cuddalore', 'school'),
('Holy Angels School Cuddalore', 'Cuddalore', 'school'),
('Sacred Heart School Cuddalore', 'Cuddalore', 'school'),
('Montfort School Cuddalore', 'Cuddalore', 'school'),
('Little Flower School Cuddalore', 'Cuddalore', 'school'),
('Government Arts College Dharmapuri', 'Dharmapuri', 'college'),
('Dharmapuri Medical College', 'Dharmapuri', 'college'),
('Dharmapuri Engineering College', 'Dharmapuri', 'college'),
('Vinayaga Arts and Science College Dharmapuri', 'Dharmapuri', 'college'),
('Meenakshi Ramasamy Arts and Science College Dharmapuri', 'Dharmapuri', 'college'),
('Modern Arts and Science College Dharmapuri', 'Dharmapuri', 'college'),
('Government Higher Secondary School Dharmapuri', 'Dharmapuri', 'school'),
('KV Dharmapuri', 'Dharmapuri', 'school'),
('PSBB School Dharmapuri', 'Dharmapuri', 'school'),
('DAV School Dharmapuri', 'Dharmapuri', 'school'),
('Don Bosco Dharmapuri', 'Dharmapuri', 'school'),
('St. Joseph's School Dharmapuri', 'Dharmapuri', 'school'),
('Holy Angels School Dharmapuri', 'Dharmapuri', 'school'),
('Sacred Heart School Dharmapuri', 'Dharmapuri', 'school'),
('Montfort School Dharmapuri', 'Dharmapuri', 'school'),
('Little Flower School Dharmapuri', 'Dharmapuri', 'school'),
('Government Arts College Dindigul', 'Dindigul', 'college'),
('Dindigul Medical College', 'Dindigul', 'college'),
('Dindigul Engineering College', 'Dindigul', 'college'),
('Vinayaga Arts and Science College Dindigul', 'Dindigul', 'college'),
('Meenakshi Ramasamy Arts and Science College Dindigul', 'Dindigul', 'college'),
('Modern Arts and Science College Dindigul', 'Dindigul', 'college'),
('Government Higher Secondary School Dindigul', 'Dindigul', 'school'),
('KV Dindigul', 'Dindigul', 'school'),
('PSBB School Dindigul', 'Dindigul', 'school'),
('DAV School Dindigul', 'Dindigul', 'school'),
('Don Bosco Dindigul', 'Dindigul', 'school'),
('St. Joseph's School Dindigul', 'Dindigul', 'school'),
('Holy Angels School Dindigul', 'Dindigul', 'school'),
('Sacred Heart School Dindigul', 'Dindigul', 'school'),
('Montfort School Dindigul', 'Dindigul', 'school'),
('Little Flower School Dindigul', 'Dindigul', 'school'),
('Government Arts College Erode', 'Erode', 'college'),
('Erode Medical College', 'Erode', 'college'),
('Erode Engineering College', 'Erode', 'college'),
('Vinayaga Arts and Science College Erode', 'Erode', 'college'),
('Meenakshi Ramasamy Arts and Science College Erode', 'Erode', 'college'),
('Modern Arts and Science College Erode', 'Erode', 'college'),
('Government Higher Secondary School Erode', 'Erode', 'school'),
('KV Erode', 'Erode', 'school'),
('PSBB School Erode', 'Erode', 'school'),
('DAV School Erode', 'Erode', 'school'),
('Don Bosco Erode', 'Erode', 'school'),
('St. Joseph's School Erode', 'Erode', 'school'),
('Holy Angels School Erode', 'Erode', 'school'),
('Sacred Heart School Erode', 'Erode', 'school'),
('Montfort School Erode', 'Erode', 'school'),
('Little Flower School Erode', 'Erode', 'school'),
('Government Arts College Kallakurichi', 'Kallakurichi', 'college'),
('Kallakurichi Medical College', 'Kallakurichi', 'college'),
('Kallakurichi Engineering College', 'Kallakurichi', 'college'),
('Vinayaga Arts and Science College Kallakurichi', 'Kallakurichi', 'college'),
('Meenakshi Ramasamy Arts and Science College Kallakurichi', 'Kallakurichi', 'college'),
('Modern Arts and Science College Kallakurichi', 'Kallakurichi', 'college'),
('Government Higher Secondary School Kallakurichi', 'Kallakurichi', 'school'),
('KV Kallakurichi', 'Kallakurichi', 'school'),
('PSBB School Kallakurichi', 'Kallakurichi', 'school'),
('DAV School Kallakurichi', 'Kallakurichi', 'school'),
('Don Bosco Kallakurichi', 'Kallakurichi', 'school'),
('St. Joseph's School Kallakurichi', 'Kallakurichi', 'school'),
('Holy Angels School Kallakurichi', 'Kallakurichi', 'school'),
('Sacred Heart School Kallakurichi', 'Kallakurichi', 'school'),
('Montfort School Kallakurichi', 'Kallakurichi', 'school'),
('Little Flower School Kallakurichi', 'Kallakurichi', 'school'),
('Government Arts College Kanchipuram', 'Kanchipuram', 'college'),
('Kanchipuram Medical College', 'Kanchipuram', 'college'),
('Kanchipuram Engineering College', 'Kanchipuram', 'college'),
('Vinayaga Arts and Science College Kanchipuram', 'Kanchipuram', 'college'),
('Meenakshi Ramasamy Arts and Science College Kanchipuram', 'Kanchipuram', 'college'),
('Modern Arts and Science College Kanchipuram', 'Kanchipuram', 'college'),
('Government Higher Secondary School Kanchipuram', 'Kanchipuram', 'school'),
('KV Kanchipuram', 'Kanchipuram', 'school'),
('PSBB School Kanchipuram', 'Kanchipuram', 'school'),
('DAV School Kanchipuram', 'Kanchipuram', 'school'),
('Don Bosco Kanchipuram', 'Kanchipuram', 'school'),
('St. Joseph's School Kanchipuram', 'Kanchipuram', 'school'),
('Holy Angels School Kanchipuram', 'Kanchipuram', 'school'),
('Sacred Heart School Kanchipuram', 'Kanchipuram', 'school'),
('Montfort School Kanchipuram', 'Kanchipuram', 'school'),
('Little Flower School Kanchipuram', 'Kanchipuram', 'school'),
('Government Arts College Kanyakumari', 'Kanyakumari', 'college'),
('Kanyakumari Medical College', 'Kanyakumari', 'college'),
('Kanyakumari Engineering College', 'Kanyakumari', 'college'),
('Vinayaga Arts and Science College Kanyakumari', 'Kanyakumari', 'college'),
('Meenakshi Ramasamy Arts and Science College Kanyakumari', 'Kanyakumari', 'college'),
('Modern Arts and Science College Kanyakumari', 'Kanyakumari', 'college'),
('Government Higher Secondary School Kanyakumari', 'Kanyakumari', 'school'),
('KV Kanyakumari', 'Kanyakumari', 'school'),
('PSBB School Kanyakumari', 'Kanyakumari', 'school'),
('DAV School Kanyakumari', 'Kanyakumari', 'school'),
('Don Bosco Kanyakumari', 'Kanyakumari', 'school'),
('St. Joseph's School Kanyakumari', 'Kanyakumari', 'school'),
('Holy Angels School Kanyakumari', 'Kanyakumari', 'school'),
('Sacred Heart School Kanyakumari', 'Kanyakumari', 'school'),
('Montfort School Kanyakumari', 'Kanyakumari', 'school'),
('Little Flower School Kanyakumari', 'Kanyakumari', 'school'),
('Government Arts College Karur', 'Karur', 'college'),
('Karur Medical College', 'Karur', 'college'),
('Karur Engineering College', 'Karur', 'college'),
('Vinayaga Arts and Science College Karur', 'Karur', 'college'),
('Meenakshi Ramasamy Arts and Science College Karur', 'Karur', 'college'),
('Modern Arts and Science College Karur', 'Karur', 'college'),
('Government Higher Secondary School Karur', 'Karur', 'school'),
('KV Karur', 'Karur', 'school'),
('PSBB School Karur', 'Karur', 'school'),
('DAV School Karur', 'Karur', 'school'),
('Don Bosco Karur', 'Karur', 'school'),
('St. Joseph's School Karur', 'Karur', 'school'),
('Holy Angels School Karur', 'Karur', 'school'),
('Sacred Heart School Karur', 'Karur', 'school'),
('Montfort School Karur', 'Karur', 'school'),
('Little Flower School Karur', 'Karur', 'school'),
('Government Arts College Krishnagiri', 'Krishnagiri', 'college'),
('Krishnagiri Medical College', 'Krishnagiri', 'college'),
('Krishnagiri Engineering College', 'Krishnagiri', 'college'),
('Vinayaga Arts and Science College Krishnagiri', 'Krishnagiri', 'college'),
('Meenakshi Ramasamy Arts and Science College Krishnagiri', 'Krishnagiri', 'college'),
('Modern Arts and Science College Krishnagiri', 'Krishnagiri', 'college'),
('Government Higher Secondary School Krishnagiri', 'Krishnagiri', 'school'),
('KV Krishnagiri', 'Krishnagiri', 'school'),
('PSBB School Krishnagiri', 'Krishnagiri', 'school'),
('DAV School Krishnagiri', 'Krishnagiri', 'school'),
('Don Bosco Krishnagiri', 'Krishnagiri', 'school'),
('St. Joseph's School Krishnagiri', 'Krishnagiri', 'school'),
('Holy Angels School Krishnagiri', 'Krishnagiri', 'school'),
('Sacred Heart School Krishnagiri', 'Krishnagiri', 'school'),
('Montfort School Krishnagiri', 'Krishnagiri', 'school'),
('Little Flower School Krishnagiri', 'Krishnagiri', 'school'),
('Madura College', 'Madurai', 'college'),
('Lady Doak College', 'Madurai', 'college'),
('American College Madurai', 'Madurai', 'college'),
('Fatima College', 'Madurai', 'college'),
('Thiagarajar College of Engineering', 'Madurai', 'college'),
('Thiagarajar College', 'Madurai', 'college'),
('Madurai Medical College', 'Madurai', 'college'),
('Velammal College of Engineering', 'Madurai', 'college'),
('Mannar Thirumalai Naicker College', 'Madurai', 'college'),
('MSS Wakf Board College', 'Madurai', 'college'),
('Government Higher Secondary School Madurai', 'Madurai', 'school'),
('KV Madurai', 'Madurai', 'school'),
('PSBB School Madurai', 'Madurai', 'school'),
('DAV School Madurai', 'Madurai', 'school'),
('Don Bosco Madurai', 'Madurai', 'school'),
('St. Joseph's School Madurai', 'Madurai', 'school'),
('Holy Angels School Madurai', 'Madurai', 'school'),
('Sacred Heart School Madurai', 'Madurai', 'school'),
('Montfort School Madurai', 'Madurai', 'school'),
('Little Flower School Madurai', 'Madurai', 'school'),
('Government Arts College Mayiladuthurai', 'Mayiladuthurai', 'college'),
('Mayiladuthurai Medical College', 'Mayiladuthurai', 'college'),
('Mayiladuthurai Engineering College', 'Mayiladuthurai', 'college'),
('Vinayaga Arts and Science College Mayiladuthurai', 'Mayiladuthurai', 'college'),
('Meenakshi Ramasamy Arts and Science College Mayiladuthurai', 'Mayiladuthurai', 'college'),
('Modern Arts and Science College Mayiladuthurai', 'Mayiladuthurai', 'college'),
('Government Higher Secondary School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('KV Mayiladuthurai', 'Mayiladuthurai', 'school'),
('PSBB School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('DAV School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('Don Bosco Mayiladuthurai', 'Mayiladuthurai', 'school'),
('St. Joseph's School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('Holy Angels School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('Sacred Heart School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('Montfort School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('Little Flower School Mayiladuthurai', 'Mayiladuthurai', 'school'),
('Government Arts College Nagapattinam', 'Nagapattinam', 'college'),
('Nagapattinam Medical College', 'Nagapattinam', 'college'),
('Nagapattinam Engineering College', 'Nagapattinam', 'college'),
('Vinayaga Arts and Science College Nagapattinam', 'Nagapattinam', 'college'),
('Meenakshi Ramasamy Arts and Science College Nagapattinam', 'Nagapattinam', 'college'),
('Modern Arts and Science College Nagapattinam', 'Nagapattinam', 'college'),
('Government Higher Secondary School Nagapattinam', 'Nagapattinam', 'school'),
('KV Nagapattinam', 'Nagapattinam', 'school'),
('PSBB School Nagapattinam', 'Nagapattinam', 'school'),
('DAV School Nagapattinam', 'Nagapattinam', 'school'),
('Don Bosco Nagapattinam', 'Nagapattinam', 'school'),
('St. Joseph's School Nagapattinam', 'Nagapattinam', 'school'),
('Holy Angels School Nagapattinam', 'Nagapattinam', 'school'),
('Sacred Heart School Nagapattinam', 'Nagapattinam', 'school'),
('Montfort School Nagapattinam', 'Nagapattinam', 'school'),
('Little Flower School Nagapattinam', 'Nagapattinam', 'school'),
('Government Arts College Namakkal', 'Namakkal', 'college'),
('Namakkal Medical College', 'Namakkal', 'college'),
('Namakkal Engineering College', 'Namakkal', 'college'),
('Vinayaga Arts and Science College Namakkal', 'Namakkal', 'college'),
('Meenakshi Ramasamy Arts and Science College Namakkal', 'Namakkal', 'college'),
('Modern Arts and Science College Namakkal', 'Namakkal', 'college'),
('Government Higher Secondary School Namakkal', 'Namakkal', 'school'),
('KV Namakkal', 'Namakkal', 'school'),
('PSBB School Namakkal', 'Namakkal', 'school'),
('DAV School Namakkal', 'Namakkal', 'school'),
('Don Bosco Namakkal', 'Namakkal', 'school'),
('St. Joseph's School Namakkal', 'Namakkal', 'school'),
('Holy Angels School Namakkal', 'Namakkal', 'school'),
('Sacred Heart School Namakkal', 'Namakkal', 'school'),
('Montfort School Namakkal', 'Namakkal', 'school'),
('Little Flower School Namakkal', 'Namakkal', 'school'),
('Government Arts College Nilgiris', 'Nilgiris', 'college'),
('Nilgiris Medical College', 'Nilgiris', 'college'),
('Nilgiris Engineering College', 'Nilgiris', 'college'),
('Vinayaga Arts and Science College Nilgiris', 'Nilgiris', 'college'),
('Meenakshi Ramasamy Arts and Science College Nilgiris', 'Nilgiris', 'college'),
('Modern Arts and Science College Nilgiris', 'Nilgiris', 'college'),
('Government Higher Secondary School Nilgiris', 'Nilgiris', 'school'),
('KV Nilgiris', 'Nilgiris', 'school'),
('PSBB School Nilgiris', 'Nilgiris', 'school'),
('DAV School Nilgiris', 'Nilgiris', 'school'),
('Don Bosco Nilgiris', 'Nilgiris', 'school'),
('St. Joseph's School Nilgiris', 'Nilgiris', 'school'),
('Holy Angels School Nilgiris', 'Nilgiris', 'school'),
('Sacred Heart School Nilgiris', 'Nilgiris', 'school'),
('Montfort School Nilgiris', 'Nilgiris', 'school'),
('Little Flower School Nilgiris', 'Nilgiris', 'school'),
('Government Arts College Perambalur', 'Perambalur', 'college'),
('Perambalur Medical College', 'Perambalur', 'college'),
('Perambalur Engineering College', 'Perambalur', 'college'),
('Vinayaga Arts and Science College Perambalur', 'Perambalur', 'college'),
('Meenakshi Ramasamy Arts and Science College Perambalur', 'Perambalur', 'college'),
('Modern Arts and Science College Perambalur', 'Perambalur', 'college'),
('Government Higher Secondary School Perambalur', 'Perambalur', 'school'),
('KV Perambalur', 'Perambalur', 'school'),
('PSBB School Perambalur', 'Perambalur', 'school'),
('DAV School Perambalur', 'Perambalur', 'school'),
('Don Bosco Perambalur', 'Perambalur', 'school'),
('St. Joseph's School Perambalur', 'Perambalur', 'school'),
('Holy Angels School Perambalur', 'Perambalur', 'school'),
('Sacred Heart School Perambalur', 'Perambalur', 'school'),
('Montfort School Perambalur', 'Perambalur', 'school'),
('Little Flower School Perambalur', 'Perambalur', 'school'),
('Government Arts College Pudukkottai', 'Pudukkottai', 'college'),
('Pudukkottai Medical College', 'Pudukkottai', 'college'),
('Pudukkottai Engineering College', 'Pudukkottai', 'college'),
('Vinayaga Arts and Science College Pudukkottai', 'Pudukkottai', 'college'),
('Meenakshi Ramasamy Arts and Science College Pudukkottai', 'Pudukkottai', 'college'),
('Modern Arts and Science College Pudukkottai', 'Pudukkottai', 'college'),
('Government Higher Secondary School Pudukkottai', 'Pudukkottai', 'school'),
('KV Pudukkottai', 'Pudukkottai', 'school'),
('PSBB School Pudukkottai', 'Pudukkottai', 'school'),
('DAV School Pudukkottai', 'Pudukkottai', 'school'),
('Don Bosco Pudukkottai', 'Pudukkottai', 'school'),
('St. Joseph's School Pudukkottai', 'Pudukkottai', 'school'),
('Holy Angels School Pudukkottai', 'Pudukkottai', 'school'),
('Sacred Heart School Pudukkottai', 'Pudukkottai', 'school'),
('Montfort School Pudukkottai', 'Pudukkottai', 'school'),
('Little Flower School Pudukkottai', 'Pudukkottai', 'school'),
('Government Arts College Ramanathapuram', 'Ramanathapuram', 'college'),
('Ramanathapuram Medical College', 'Ramanathapuram', 'college'),
('Ramanathapuram Engineering College', 'Ramanathapuram', 'college'),
('Vinayaga Arts and Science College Ramanathapuram', 'Ramanathapuram', 'college'),
('Meenakshi Ramasamy Arts and Science College Ramanathapuram', 'Ramanathapuram', 'college'),
('Modern Arts and Science College Ramanathapuram', 'Ramanathapuram', 'college'),
('Government Higher Secondary School Ramanathapuram', 'Ramanathapuram', 'school'),
('KV Ramanathapuram', 'Ramanathapuram', 'school'),
('PSBB School Ramanathapuram', 'Ramanathapuram', 'school'),
('DAV School Ramanathapuram', 'Ramanathapuram', 'school'),
('Don Bosco Ramanathapuram', 'Ramanathapuram', 'school'),
('St. Joseph's School Ramanathapuram', 'Ramanathapuram', 'school'),
('Holy Angels School Ramanathapuram', 'Ramanathapuram', 'school'),
('Sacred Heart School Ramanathapuram', 'Ramanathapuram', 'school'),
('Montfort School Ramanathapuram', 'Ramanathapuram', 'school'),
('Little Flower School Ramanathapuram', 'Ramanathapuram', 'school'),
('Government Arts College Ranipet', 'Ranipet', 'college'),
('Ranipet Medical College', 'Ranipet', 'college'),
('Ranipet Engineering College', 'Ranipet', 'college'),
('Vinayaga Arts and Science College Ranipet', 'Ranipet', 'college'),
('Meenakshi Ramasamy Arts and Science College Ranipet', 'Ranipet', 'college'),
('Modern Arts and Science College Ranipet', 'Ranipet', 'college'),
('Government Higher Secondary School Ranipet', 'Ranipet', 'school'),
('KV Ranipet', 'Ranipet', 'school'),
('PSBB School Ranipet', 'Ranipet', 'school'),
('DAV School Ranipet', 'Ranipet', 'school'),
('Don Bosco Ranipet', 'Ranipet', 'school'),
('St. Joseph's School Ranipet', 'Ranipet', 'school'),
('Holy Angels School Ranipet', 'Ranipet', 'school'),
('Sacred Heart School Ranipet', 'Ranipet', 'school'),
('Montfort School Ranipet', 'Ranipet', 'school'),
('Little Flower School Ranipet', 'Ranipet', 'school'),
('Government Arts College Salem', 'Salem', 'college'),
('Salem Medical College', 'Salem', 'college'),
('Salem Engineering College', 'Salem', 'college'),
('Vinayaga Arts and Science College Salem', 'Salem', 'college'),
('Meenakshi Ramasamy Arts and Science College Salem', 'Salem', 'college'),
('Modern Arts and Science College Salem', 'Salem', 'college'),
('Government Higher Secondary School Salem', 'Salem', 'school'),
('KV Salem', 'Salem', 'school'),
('PSBB School Salem', 'Salem', 'school'),
('DAV School Salem', 'Salem', 'school'),
('Don Bosco Salem', 'Salem', 'school'),
('St. Joseph's School Salem', 'Salem', 'school'),
('Holy Angels School Salem', 'Salem', 'school'),
('Sacred Heart School Salem', 'Salem', 'school'),
('Montfort School Salem', 'Salem', 'school'),
('Little Flower School Salem', 'Salem', 'school'),
('Government Arts College Sivagangai', 'Sivagangai', 'college'),
('Sivagangai Medical College', 'Sivagangai', 'college'),
('Sivagangai Engineering College', 'Sivagangai', 'college'),
('Vinayaga Arts and Science College Sivagangai', 'Sivagangai', 'college'),
('Meenakshi Ramasamy Arts and Science College Sivagangai', 'Sivagangai', 'college'),
('Modern Arts and Science College Sivagangai', 'Sivagangai', 'college'),
('Government Higher Secondary School Sivagangai', 'Sivagangai', 'school'),
('KV Sivagangai', 'Sivagangai', 'school'),
('PSBB School Sivagangai', 'Sivagangai', 'school'),
('DAV School Sivagangai', 'Sivagangai', 'school'),
('Don Bosco Sivagangai', 'Sivagangai', 'school'),
('St. Joseph's School Sivagangai', 'Sivagangai', 'school'),
('Holy Angels School Sivagangai', 'Sivagangai', 'school'),
('Sacred Heart School Sivagangai', 'Sivagangai', 'school'),
('Montfort School Sivagangai', 'Sivagangai', 'school'),
('Little Flower School Sivagangai', 'Sivagangai', 'school'),
('Government Arts College Tenkasi', 'Tenkasi', 'college'),
('Tenkasi Medical College', 'Tenkasi', 'college'),
('Tenkasi Engineering College', 'Tenkasi', 'college'),
('Vinayaga Arts and Science College Tenkasi', 'Tenkasi', 'college'),
('Meenakshi Ramasamy Arts and Science College Tenkasi', 'Tenkasi', 'college'),
('Modern Arts and Science College Tenkasi', 'Tenkasi', 'college'),
('Government Higher Secondary School Tenkasi', 'Tenkasi', 'school'),
('KV Tenkasi', 'Tenkasi', 'school'),
('PSBB School Tenkasi', 'Tenkasi', 'school'),
('DAV School Tenkasi', 'Tenkasi', 'school'),
('Don Bosco Tenkasi', 'Tenkasi', 'school'),
('St. Joseph's School Tenkasi', 'Tenkasi', 'school'),
('Holy Angels School Tenkasi', 'Tenkasi', 'school'),
('Sacred Heart School Tenkasi', 'Tenkasi', 'school'),
('Montfort School Tenkasi', 'Tenkasi', 'school'),
('Little Flower School Tenkasi', 'Tenkasi', 'school'),
('Government Arts College Thanjavur', 'Thanjavur', 'college'),
('Thanjavur Medical College', 'Thanjavur', 'college'),
('Thanjavur Engineering College', 'Thanjavur', 'college'),
('Vinayaga Arts and Science College Thanjavur', 'Thanjavur', 'college'),
('Meenakshi Ramasamy Arts and Science College Thanjavur', 'Thanjavur', 'college'),
('Modern Arts and Science College Thanjavur', 'Thanjavur', 'college'),
('Government Higher Secondary School Thanjavur', 'Thanjavur', 'school'),
('KV Thanjavur', 'Thanjavur', 'school'),
('PSBB School Thanjavur', 'Thanjavur', 'school'),
('DAV School Thanjavur', 'Thanjavur', 'school'),
('Don Bosco Thanjavur', 'Thanjavur', 'school'),
('St. Joseph's School Thanjavur', 'Thanjavur', 'school'),
('Holy Angels School Thanjavur', 'Thanjavur', 'school'),
('Sacred Heart School Thanjavur', 'Thanjavur', 'school'),
('Montfort School Thanjavur', 'Thanjavur', 'school'),
('Little Flower School Thanjavur', 'Thanjavur', 'school'),
('Government Arts College Theni', 'Theni', 'college'),
('Theni Medical College', 'Theni', 'college'),
('Theni Engineering College', 'Theni', 'college'),
('Vinayaga Arts and Science College Theni', 'Theni', 'college'),
('Meenakshi Ramasamy Arts and Science College Theni', 'Theni', 'college'),
('Modern Arts and Science College Theni', 'Theni', 'college'),
('Government Higher Secondary School Theni', 'Theni', 'school'),
('KV Theni', 'Theni', 'school'),
('PSBB School Theni', 'Theni', 'school'),
('DAV School Theni', 'Theni', 'school'),
('Don Bosco Theni', 'Theni', 'school'),
('St. Joseph's School Theni', 'Theni', 'school'),
('Holy Angels School Theni', 'Theni', 'school'),
('Sacred Heart School Theni', 'Theni', 'school'),
('Montfort School Theni', 'Theni', 'school'),
('Little Flower School Theni', 'Theni', 'school'),
('Government Arts College Thoothukudi', 'Thoothukudi', 'college'),
('Thoothukudi Medical College', 'Thoothukudi', 'college'),
('Thoothukudi Engineering College', 'Thoothukudi', 'college'),
('Vinayaga Arts and Science College Thoothukudi', 'Thoothukudi', 'college'),
('Meenakshi Ramasamy Arts and Science College Thoothukudi', 'Thoothukudi', 'college'),
('Modern Arts and Science College Thoothukudi', 'Thoothukudi', 'college'),
('Government Higher Secondary School Thoothukudi', 'Thoothukudi', 'school'),
('KV Thoothukudi', 'Thoothukudi', 'school'),
('PSBB School Thoothukudi', 'Thoothukudi', 'school'),
('DAV School Thoothukudi', 'Thoothukudi', 'school'),
('Don Bosco Thoothukudi', 'Thoothukudi', 'school'),
('St. Joseph's School Thoothukudi', 'Thoothukudi', 'school'),
('Holy Angels School Thoothukudi', 'Thoothukudi', 'school'),
('Sacred Heart School Thoothukudi', 'Thoothukudi', 'school'),
('Montfort School Thoothukudi', 'Thoothukudi', 'school'),
('Little Flower School Thoothukudi', 'Thoothukudi', 'school'),
('St. Joseph's College Trichy', 'Tiruchirappalli', 'college'),
('National Institute of Technology Trichy', 'Tiruchirappalli', 'college'),
('Bishop Heber College', 'Tiruchirappalli', 'college'),
('Holy Cross College Trichy', 'Tiruchirappalli', 'college'),
('Jamal Mohamed College', 'Tiruchirappalli', 'college'),
('Bharathidasan University', 'Tiruchirappalli', 'college'),
('K. Ramakrishnan College of Technology', 'Tiruchirappalli', 'college'),
('M.A.M. College of Engineering', 'Tiruchirappalli', 'college'),
('Srimad Andavan Arts and Science College', 'Tiruchirappalli', 'college'),
('Government Arts College Trichy', 'Tiruchirappalli', 'college'),
('Government Higher Secondary School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('KV Tiruchirappalli', 'Tiruchirappalli', 'school'),
('PSBB School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('DAV School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('Don Bosco Tiruchirappalli', 'Tiruchirappalli', 'school'),
('St. Joseph's School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('Holy Angels School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('Sacred Heart School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('Montfort School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('Little Flower School Tiruchirappalli', 'Tiruchirappalli', 'school'),
('Government Arts College Tirunelveli', 'Tirunelveli', 'college'),
('Tirunelveli Medical College', 'Tirunelveli', 'college'),
('Tirunelveli Engineering College', 'Tirunelveli', 'college'),
('Vinayaga Arts and Science College Tirunelveli', 'Tirunelveli', 'college'),
('Meenakshi Ramasamy Arts and Science College Tirunelveli', 'Tirunelveli', 'college'),
('Modern Arts and Science College Tirunelveli', 'Tirunelveli', 'college'),
('Government Higher Secondary School Tirunelveli', 'Tirunelveli', 'school'),
('KV Tirunelveli', 'Tirunelveli', 'school'),
('PSBB School Tirunelveli', 'Tirunelveli', 'school'),
('DAV School Tirunelveli', 'Tirunelveli', 'school'),
('Don Bosco Tirunelveli', 'Tirunelveli', 'school'),
('St. Joseph's School Tirunelveli', 'Tirunelveli', 'school'),
('Holy Angels School Tirunelveli', 'Tirunelveli', 'school'),
('Sacred Heart School Tirunelveli', 'Tirunelveli', 'school'),
('Montfort School Tirunelveli', 'Tirunelveli', 'school'),
('Little Flower School Tirunelveli', 'Tirunelveli', 'school'),
('Government Arts College Tirupathur', 'Tirupathur', 'college'),
('Tirupathur Medical College', 'Tirupathur', 'college'),
('Tirupathur Engineering College', 'Tirupathur', 'college'),
('Vinayaga Arts and Science College Tirupathur', 'Tirupathur', 'college'),
('Meenakshi Ramasamy Arts and Science College Tirupathur', 'Tirupathur', 'college'),
('Modern Arts and Science College Tirupathur', 'Tirupathur', 'college'),
('Government Higher Secondary School Tirupathur', 'Tirupathur', 'school'),
('KV Tirupathur', 'Tirupathur', 'school'),
('PSBB School Tirupathur', 'Tirupathur', 'school'),
('DAV School Tirupathur', 'Tirupathur', 'school'),
('Don Bosco Tirupathur', 'Tirupathur', 'school'),
('St. Joseph's School Tirupathur', 'Tirupathur', 'school'),
('Holy Angels School Tirupathur', 'Tirupathur', 'school'),
('Sacred Heart School Tirupathur', 'Tirupathur', 'school'),
('Montfort School Tirupathur', 'Tirupathur', 'school'),
('Little Flower School Tirupathur', 'Tirupathur', 'school'),
('Government Arts College Tiruppur', 'Tiruppur', 'college'),
('Tiruppur Medical College', 'Tiruppur', 'college'),
('Tiruppur Engineering College', 'Tiruppur', 'college'),
('Vinayaga Arts and Science College Tiruppur', 'Tiruppur', 'college'),
('Meenakshi Ramasamy Arts and Science College Tiruppur', 'Tiruppur', 'college'),
('Modern Arts and Science College Tiruppur', 'Tiruppur', 'college'),
('Government Higher Secondary School Tiruppur', 'Tiruppur', 'school'),
('KV Tiruppur', 'Tiruppur', 'school'),
('PSBB School Tiruppur', 'Tiruppur', 'school'),
('DAV School Tiruppur', 'Tiruppur', 'school'),
('Don Bosco Tiruppur', 'Tiruppur', 'school'),
('St. Joseph's School Tiruppur', 'Tiruppur', 'school'),
('Holy Angels School Tiruppur', 'Tiruppur', 'school'),
('Sacred Heart School Tiruppur', 'Tiruppur', 'school'),
('Montfort School Tiruppur', 'Tiruppur', 'school'),
('Little Flower School Tiruppur', 'Tiruppur', 'school'),
('Government Arts College Tiruvallur', 'Tiruvallur', 'college'),
('Tiruvallur Medical College', 'Tiruvallur', 'college'),
('Tiruvallur Engineering College', 'Tiruvallur', 'college'),
('Vinayaga Arts and Science College Tiruvallur', 'Tiruvallur', 'college'),
('Meenakshi Ramasamy Arts and Science College Tiruvallur', 'Tiruvallur', 'college'),
('Modern Arts and Science College Tiruvallur', 'Tiruvallur', 'college'),
('Government Higher Secondary School Tiruvallur', 'Tiruvallur', 'school'),
('KV Tiruvallur', 'Tiruvallur', 'school'),
('PSBB School Tiruvallur', 'Tiruvallur', 'school'),
('DAV School Tiruvallur', 'Tiruvallur', 'school'),
('Don Bosco Tiruvallur', 'Tiruvallur', 'school'),
('St. Joseph's School Tiruvallur', 'Tiruvallur', 'school'),
('Holy Angels School Tiruvallur', 'Tiruvallur', 'school'),
('Sacred Heart School Tiruvallur', 'Tiruvallur', 'school'),
('Montfort School Tiruvallur', 'Tiruvallur', 'school'),
('Little Flower School Tiruvallur', 'Tiruvallur', 'school'),
('Government Arts College Tiruvannamalai', 'Tiruvannamalai', 'college'),
('Tiruvannamalai Medical College', 'Tiruvannamalai', 'college'),
('Tiruvannamalai Engineering College', 'Tiruvannamalai', 'college'),
('Vinayaga Arts and Science College Tiruvannamalai', 'Tiruvannamalai', 'college'),
('Meenakshi Ramasamy Arts and Science College Tiruvannamalai', 'Tiruvannamalai', 'college'),
('Modern Arts and Science College Tiruvannamalai', 'Tiruvannamalai', 'college'),
('Government Higher Secondary School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('KV Tiruvannamalai', 'Tiruvannamalai', 'school'),
('PSBB School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('DAV School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('Don Bosco Tiruvannamalai', 'Tiruvannamalai', 'school'),
('St. Joseph's School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('Holy Angels School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('Sacred Heart School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('Montfort School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('Little Flower School Tiruvannamalai', 'Tiruvannamalai', 'school'),
('Government Arts College Tiruvarur', 'Tiruvarur', 'college'),
('Tiruvarur Medical College', 'Tiruvarur', 'college'),
('Tiruvarur Engineering College', 'Tiruvarur', 'college'),
('Vinayaga Arts and Science College Tiruvarur', 'Tiruvarur', 'college'),
('Meenakshi Ramasamy Arts and Science College Tiruvarur', 'Tiruvarur', 'college'),
('Modern Arts and Science College Tiruvarur', 'Tiruvarur', 'college'),
('Government Higher Secondary School Tiruvarur', 'Tiruvarur', 'school'),
('KV Tiruvarur', 'Tiruvarur', 'school'),
('PSBB School Tiruvarur', 'Tiruvarur', 'school'),
('DAV School Tiruvarur', 'Tiruvarur', 'school'),
('Don Bosco Tiruvarur', 'Tiruvarur', 'school'),
('St. Joseph's School Tiruvarur', 'Tiruvarur', 'school'),
('Holy Angels School Tiruvarur', 'Tiruvarur', 'school'),
('Sacred Heart School Tiruvarur', 'Tiruvarur', 'school'),
('Montfort School Tiruvarur', 'Tiruvarur', 'school'),
('Little Flower School Tiruvarur', 'Tiruvarur', 'school'),
('Government Arts College Vellore', 'Vellore', 'college'),
('Vellore Medical College', 'Vellore', 'college'),
('Vellore Engineering College', 'Vellore', 'college'),
('Vinayaga Arts and Science College Vellore', 'Vellore', 'college'),
('Meenakshi Ramasamy Arts and Science College Vellore', 'Vellore', 'college'),
('Modern Arts and Science College Vellore', 'Vellore', 'college'),
('Government Higher Secondary School Vellore', 'Vellore', 'school'),
('KV Vellore', 'Vellore', 'school'),
('PSBB School Vellore', 'Vellore', 'school'),
('DAV School Vellore', 'Vellore', 'school'),
('Don Bosco Vellore', 'Vellore', 'school'),
('St. Joseph's School Vellore', 'Vellore', 'school'),
('Holy Angels School Vellore', 'Vellore', 'school'),
('Sacred Heart School Vellore', 'Vellore', 'school'),
('Montfort School Vellore', 'Vellore', 'school'),
('Little Flower School Vellore', 'Vellore', 'school'),
('Government Arts College Viluppuram', 'Viluppuram', 'college'),
('Viluppuram Medical College', 'Viluppuram', 'college'),
('Viluppuram Engineering College', 'Viluppuram', 'college'),
('Vinayaga Arts and Science College Viluppuram', 'Viluppuram', 'college'),
('Meenakshi Ramasamy Arts and Science College Viluppuram', 'Viluppuram', 'college'),
('Modern Arts and Science College Viluppuram', 'Viluppuram', 'college'),
('Government Higher Secondary School Viluppuram', 'Viluppuram', 'school'),
('KV Viluppuram', 'Viluppuram', 'school'),
('PSBB School Viluppuram', 'Viluppuram', 'school'),
('DAV School Viluppuram', 'Viluppuram', 'school'),
('Don Bosco Viluppuram', 'Viluppuram', 'school'),
('St. Joseph's School Viluppuram', 'Viluppuram', 'school'),
('Holy Angels School Viluppuram', 'Viluppuram', 'school'),
('Sacred Heart School Viluppuram', 'Viluppuram', 'school'),
('Montfort School Viluppuram', 'Viluppuram', 'school'),
('Little Flower School Viluppuram', 'Viluppuram', 'school'),
('Government Arts College Virudhunagar', 'Virudhunagar', 'college'),
('Virudhunagar Medical College', 'Virudhunagar', 'college'),
('Virudhunagar Engineering College', 'Virudhunagar', 'college'),
('Vinayaga Arts and Science College Virudhunagar', 'Virudhunagar', 'college'),
('Meenakshi Ramasamy Arts and Science College Virudhunagar', 'Virudhunagar', 'college'),
('Modern Arts and Science College Virudhunagar', 'Virudhunagar', 'college'),
('Government Higher Secondary School Virudhunagar', 'Virudhunagar', 'school'),
('KV Virudhunagar', 'Virudhunagar', 'school'),
('PSBB School Virudhunagar', 'Virudhunagar', 'school'),
('DAV School Virudhunagar', 'Virudhunagar', 'school'),
('Don Bosco Virudhunagar', 'Virudhunagar', 'school'),
('St. Joseph's School Virudhunagar', 'Virudhunagar', 'school'),
('Holy Angels School Virudhunagar', 'Virudhunagar', 'school'),
('Sacred Heart School Virudhunagar', 'Virudhunagar', 'school'),
('Montfort School Virudhunagar', 'Virudhunagar', 'school'),
('Little Flower School Virudhunagar', 'Virudhunagar', 'school');
