const districtTowns = {
  'Ariyalur': ['Ariyalur', 'Jayankondam', 'Sendurai', 'Udayarpalayam'],
  'Chengalpattu': ['Chengalpattu', 'Maduranthakam', 'Tambaram', 'Pallavaram', 'Vandalur', 'Marakkanam', 'Cheyyur'],
  'Coimbatore': ['Coimbatore', 'Pollachi', 'Mettupalayam', 'Sulur', 'Thudiyalur', 'Annur', 'Valparai', 'Periyanaickenpalayam'],
  'Cuddalore': ['Cuddalore', 'Chidambaram', 'Panruti', 'Vriddhachalam', 'Neyveli', 'Kattuparankunram'],
  'Dharmapuri': ['Dharmapuri', 'Palacode', 'Pennagaram', 'Harur', 'Pappireddipatti'],
  'Dindigul': ['Dindigul', 'Palani', 'Oddanchatram', 'Kodaikanal', 'Natham', 'Nilakottai', 'Vedansandur'],
  'Erode': ['Erode', 'Gobichettipalayam', 'Bhavani', 'Perundurai', 'Sathyamangalam', 'Anthiyur'],
  'Kallakurichi': ['Kallakurichi', 'Sankarapuram', 'Tirukkoyilur', 'Ulundurpet'],
  'Kanchipuram': ['Kanchipuram', 'Sriperumbudur', 'Walajabad', 'Kundrathur', 'Uthiramerur'],
  'Kanyakumari': ['Nagercoil', 'Kanyakumari', 'Padmanabhapuram', 'Kuzhithurai', 'Colachel'],
  'Karur': ['Karur', 'Kulithalai', 'Aravakurichi', 'Krishnarayapuram'],
  'Krishnagiri': ['Krishnagiri', 'Hosur', 'Denkanikottai', 'Pochampalli', 'Uthangarai'],
  'Madurai': ['Madurai', 'Melur', 'Thirumangalam', 'Usilampatti', 'Vadipatti', 'Thirupparankundram'],
  'Mayiladuthurai': ['Mayiladuthurai', 'Sirkazhi', 'Tharangambadi', 'Kuthalam'],
  'Nagapattinam': ['Nagapattinam', 'Velankanni', 'Thirukkuvalai', 'Vedaranyam', 'Kilvelur'],
  'Namakkal': ['Namakkal', 'Rasipuram', 'Tiruchengode', 'Komarapalayam', 'Paramathi Velur'],
  'Nilgiris': ['Ooty', 'Coonoor', 'Gudalur', 'Kotagiri', 'Kundah'],
  'Perambalur': ['Perambalur', 'Kunnam', 'Veppanthattai', 'Alathur'],
  'Pudukkottai': ['Pudukkottai', 'Aranthangi', 'Illuppur', 'Kulathur', 'Gandarvakottai'],
  'Ramanathapuram': ['Ramanathapuram', 'Paramakudi', 'Rameswaram', 'Kamuthi', 'Mudukulathur'],
  'Ranipet': ['Ranipet', 'Arcot', 'Walajah', 'Arakkonam', 'Nemili'],
  'Salem': ['Salem', 'Attur', 'Mettur', 'Sangagiri', 'Omalur', 'Edappadi', 'Yercaud'],
  'Sivagangai': ['Sivagangai', 'Karaikudi', 'Devakottai', 'Manamadurai', 'Ilayangudi'],
  'Tenkasi': ['Tenkasi', 'Sankarankovil', 'Kadayanallur', 'Alangulam', 'Shenkottai'],
  'Thanjavur': ['Thanjavur', 'Kumbakonam', 'Pattukkottai', 'Orathanadu', 'Thiruvaiyaru', 'Papanasam'],
  'Theni': ['Theni', 'Periyakulam', 'Bodinayakanur', 'Cumbum', 'Uthamapalayam'],
  'Thoothukudi': ['Thoothukudi', 'Kovilpatti', 'Tiruchendur', 'Srivaikuntam', 'Vilathikulam'],
  'Tiruchirappalli': ['Trichy', 'Srirangam', 'Thiruverumbur', 'Musiri', 'Lalgudi', 'Thuraiyur', 'Manapparai'],
  'Tirunelveli': ['Tirunelveli', 'Palayamkottai', 'Ambasamudram', 'Nanguneri', 'Radhapuram'],
  'Tirupathur': ['Tirupathur', 'Vaniyambadi', 'Ambur', 'Natrampalli'],
  'Tiruppur': ['Tiruppur', 'Dharapuram', 'Kangeyam', 'Uthukuli', 'Palladam', 'Udumalaipettai'],
  'Tiruvallur': ['Tiruvallur', 'Avadi', 'Poonamallee', 'Tiruttani', 'Gummidipoondi', 'Ponneri'],
  'Tiruvannamalai': ['Tiruvannamalai', 'Arani', 'Cheyyar', 'Vandavasi', 'Polur', 'Chengam'],
  'Tiruvarur': ['Tiruvarur', 'Mannargudi', 'Thiruthuraipoondi', 'Nannilam', 'Needamangalam'],
  'Vellore': ['Vellore', 'Katpadi', 'Gudiyatham', 'Pernambut', 'Anaicut'],
  'Viluppuram': ['Viluppuram', 'Tindivanam', 'Gingee', 'Vikravandi', 'Vanur'],
  'Virudhunagar': ['Virudhunagar', 'Sivakasi', 'Rajapalayam', 'Aruppukkottai', 'Sattur', 'Srivilliputhur']
};

console.log('Town mapping prepared for 37 districts.');
exports.districtTowns = districtTowns;
